# manifests/infrastructure/ollama/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama-helm
  namespace: flux-system
spec:
  interval: 1h
  url: https://otwld.github.io/ollama-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 5m
  timeout: 3m
  chart:
    spec:
      chart: ollama
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    runtimeClassName: "nvidia"
    replicaCount: 1
    knative:
      enabled: false
    image:
      repository: ollama/ollama
      pullPolicy: IfNotPresent
    ollama:
      gpu:
        enabled: true
        type: "nvidia"
        number: 1
        nvidiaResource: "nvidia.com/gpu"
        mig:
          enabled: false
      models:
        pull:
        - llama4
        run:
        - llama4
      service:
        type: NodePort
        port: 11434
        nodePort: 31434
