# /Users/rvs/Repositories/SVNs/Github-Rahulsharma0810/271_Labs/HomeLab-Kubernetes/manifests/infrastructure/ollama/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama-helm
  namespace: flux-system
spec:
  interval: 1h
  url: https://otwld.github.io/ollama-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 5m
  timeout: 3m
  chart:
    spec:
      chart: ollama
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistentVolume:
      enabled: true
      existingClaim: "ollama-pvc"
      mountPath: "/root/.ollama"
    extraEnv:
    - name: OLLAMA_DEBUG
      value: "1"
    # - name: OLLAMA_MAX_LOADED_MODELS
    #   value: "1"
    # - name: OLLAMA_KEEP_ALIVE
    #   value: "3m"
    # - name: OLLAMA_MAX_VRAM
    #   value: "20Gi"
    runtimeClassName: "nvidia"
    replicaCount: 1
    knative:
      enabled: false
    image:
      repository: ollama/ollama
      pullPolicy: Always
      tag: latest
    ollama:
      gpu:
        enabled: true
        type: "nvidia"
        number: 1
        nvidiaResource: "nvidia.com/gpu"
        mig:
          enabled: false
      models:
        pull:
        - qwen3:8b
        - qwen2.5vl
        - gpt-oss:20b
        run:
        - qwen3:8b
        - qwen2.5vl
        - gpt-oss:20b
        clean: true
    service:
      type: NodePort
      port: 11434
      nodePort: 30434
