# manifests/infrastructure/ollama/tunnel-binding-ingress.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: ollama-tunnel-binding
  namespace: ollama
subjects:
- name: ollama
  spec:
    fqdn: ollama.rvsharma.com
tunnelRef:
  kind: ClusterTunnel
  name: i1-1806-talos-proxmox-cluster-tunnel
