# manifests/infrastructure/mcp-servers/mcpo/deployment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
  namespace: mcp-servers
data:
  config.json: |
    {
      "mcpServers": {
        "firefly": {
          "type": "streamable-http",
          "url": "http://firefly-mcp-service.mcp-servers.svc.cluster.local/mcp"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpo-gateway
  namespace: mcp-servers
spec:
  replicas: 1
  selector:
    matchLabels: { app: mcpo-gateway }
  template:
    metadata:
      labels: { app: mcpo-gateway }
    spec:
      containers:
      - name: mcpo
        image: ghcr.io/open-webui/mcpo:main
        args:
        - "--host=0.0.0.0"
        - "--port=8000"
        - "--config=/config/config.json"
        - "--hot-reload"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: cfg
          mountPath: /config
      volumes:
      - name: cfg
        configMap:
          name: mcpo-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcpo-gateway
  namespace: mcp-servers
spec:
  type: NodePort
  selector: { app: mcpo-gateway }
  ports:
  - name: http
    targetPort: 8000
    port: 8000
    nodePort: 32000
    
