# manifests/infrastructure/control-plane-ingress/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- clusterrolebinding.yaml
- serviceacount.yaml
- tunnel-binding-ingress.yaml
