apiVersion: v1
kind: Service
metadata:
  name: k8s-api-tunnel-binding-svc
  namespace: kube-system
  labels:
    app: kubernetes-api
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 6443
      protocol: TCP
  selector:
    component: kube-apiserver
