# manifests/infrastructure/control-plane-ingress/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: kube-system
spec:
  selector: {}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 6443
    name: https
  externalName: 192.168.0.5
