apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: k8s-api-tunnel-binding
  namespace: kube-system
subjects:
- name: k8s-api-svc
  spec:
    fqdn: kubernetes.rvsharma.com
    protocol: https
    noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: i1-1806-talos-proxmox-cluster-tunnel
