apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-wildcard-rvsharma-cert-secret
  namespace: cert-manager
spec:
  secretName: ca-wildcard-rvsharma-cert-secret
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - "*.rvsharma.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/auto-reflects: ca-wildcard-rvsharma-cert-secret
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ".*" # Control auto-reflection namespaces
