# manifests/infrastructure/secrets/n8n-system/enc_key.yaml
apiVersion: v1
kind: Secret
metadata:
    name: n8n-encryption-key
    namespace: n8n-system
type: Opaque
stringData:
    encryption_key: ENC[AES256_GCM,data:vg4zMo/wYCTlCt2H1js37f4C4JShS3z/GinFgYc48hpqCBYyOgI6P1/jAuEh+ZShs6FEm89IpCgjp97Y0VFNzLXpcuzXYmjoCDY2RbGTdW2s1GCcxVrYxA==,iv:iPaEEPSAZmNWKYT9qenvaG1vQ1aadfDw6A24z19LBQ0=,tag:PdZkoGMGuniBYVwDTH77Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NW9rUHNJQkxpd3dEZzMw
            dUJ6bm5XQXhhOXpRL0puRHlCN1ZNdHhDekZrCkFIeUR0ZEdzSHVjMlFya0pOUW5i
            cHZCZlZLcXBKU3BldVQ4UTZkWlVsaWMKLS0tIGpLMTZvQTVyTnNtYmZIZXc2bi8x
            ejBEOXpGY004cThqeEJ5RnFpSi9UWlUKc+FeYF+P/Td9i2Xu+iuow1lWvvpPC1Dg
            ecHfIrOkBwfMBqGztF037JR+DeLPf47/iNF6rDyY+J7/n4yg1eVnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T11:30:50Z"
    mac: ENC[AES256_GCM,data:ZaWGyDdJ8/VSmFTgtalzRQ2O4hdh9gwTCxzmIFuCJ8aXnzwu6l8WMuxvIxWblp0L75YBdr1GVDGErwGkOsq8iXu6+Ymkpn9ytcFJZaMGZmUNkfvcr5GGa+pdx0EoYAcLG+udufC+Za4PFEVIw1B2Fd8h8KVOaSSSOiVQaZc/krE=,iv:k6AdPgRsX24YqniEyCaXt2qQD7QBLIQ0QV4X6WRZIeQ=,tag:QWLGvnd67yraoS4INOjxIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
