# HomeLab-Kubernetes/manifests/infrastructure/paperless-system/pre-consumption.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: paperlessngx-scripts
    namespace: paperless-system
data:
    unlock.py: |
        #!/usr/bin/env python
        import pikepdf
        import os

        def unlock_pdf(file_path):
            # Check if the file is a PDF
            if not file_path.endswith(".pdf"):
                print(f"Skipping non-PDF file: {file_path}")
                return

            passwords = [
                os.getenv('PASSWORD_1'),
                os.getenv('PASSWORD_2'),
                os.getenv('PASSWORD_3'),
                os.getenv('PASSWORD_4'),
                os.getenv('PASSWORD_5')
            ]

            for password in passwords:
                if password is None:
                    continue
                try:
                    with pikepdf.open(file_path, password=password, allow_overwriting_input=True) as pdf:
                        print(f"Password is working: {password}")
                        pdf.save(file_path)
                        break
                except pikepdf.PasswordError:
                    print(f"Password isn't working: {password}")
                    continue
            else:
                print("No valid password found")

        file_path = os.getenv('DOCUMENT_WORKING_PATH')
        if file_path:
            unlock_pdf(file_path)
        else:
            print("DOCUMENT_WORKING_PATH environment variable is not set.")
