apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: paperless-tunnel-binding
  namespace: paperless-system
subjects:
- name: paperlessngx-service
  spec:
    fqdn: paper.rvsharma.com
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: paperlessai-tunnel-binding
  namespace: paperless-system
subjects:
- name: paperless-ai-service
  spec:
    fqdn: paperai.rvsharma.com
