# HomeLab-Kubernetes/manifests/infrastructure/redis-operator/redis-immich-cluster.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-redis-pv
  namespace: cnrds-system
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: "redis-immich-manual"
  hostPath:
    path: /var/mnt/ssd_nvme_predator_GM7000/redis-operator/immich
    type: DirectoryOrCreate
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis-immich-cluster
  namespace: cnrds-system
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:latest
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  nodeSelector:
    kubernetes.io/hostname: i1-1806-talos-worker01
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "redis-immich-manual"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        volumeName: immich-redis-pv
