# manifests/infrastructure/secrets/cloudflare/zero-trust-secret.yaml
apiVersion: v1
metadata:
    name: cloudflare-zero-trust-secret
    namespace: cloudflare-operator-system
kind: Secret
type: Opaque
stringData:
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:RgbieoxzB7o4RALppGQQf5NGoQtgd8sMvbUCUd3AyP0=,iv:6ShHbgh/NtTVbJVaV4dtqMJCiTrnGf4nSe8obG6dOOk=,tag:6Sm9ljiExS6ukPdkl1GWbA==,type:str]
    #ENC[AES256_GCM,data:eiea0VuqtnaY8130HdPayVOkdxURy6N4oHtDa0jy0riYsLr9jaiYBuE+Rg==,iv:Dy6V1ckRlzBrSaC3bnGggeM5YXJoejNmAxfyaDOzlOQ=,tag:BJ30Jt9OwuIXy4dVXCSlpw==,type:comment]
    #ENC[AES256_GCM,data:gu8gEdTuQwdTUWuKlsP7EO5RetE42pqhNUtlAxVUE3aHUv8IrsJvaDHVsVNWnFHwB84vzRGNFZE=,iv:SDu3kwCVoN0j4kdDo0XP2p6K0wCNjLrDkSk3v0bbaNE=,tag:EEAT4mTA0EHhDqWC63m3Fg==,type:comment]
    CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:TbqR403qmwz2SwjM4Hs+5YByYCqm,iv:34/hTWbqWu4OkApgyYauTaF274QtDdOztIhPp6wwC4M=,tag:vRYiu3jCdhJVUk+/qPyKXA==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:2+RSieE0Qx5bwZd12J66OfYZpElj4wF3hhIUJUNIHx1tH3RzxZbHfPkfzR55KDfmPOL1yQ==,iv:iklImNbU8kqdPPBwgNvXOOZkHnJP6nUgxTLUBQn3WLs=,tag:zVzQDEhIZaKSP3gn1rDfcA==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:t7q7kCePWhRn/RHyHONGM1PwmcvBPuIJxj1JMon30C842Za6XmiWLxSaYGTQUB6d3VWEtbyabkU=,iv:JEalG15tno6P4F5+PM7jtVdzhzuVVV6j+dZJXG4F814=,tag:YIhtP1Iqm6pJc04SUrKRxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdkIxZjkzOUR1d2NySDln
            a3E4dGY5dFR3Nm13eU5pRjdrRXNUK2t4TkZBCkVlWTdjRlBzSUFuUHlrMDJwWFhm
            RnJmWjZNOFhtK2REYjhpYTFLK2lLQUkKLS0tIHg2Z3BHdXpZY1A4OWxDQkJjMjlE
            SUNCVVIxUzNkLzFGTERSWHAzOGM0YW8KFKk0xQHxVnRcYY419O9ZdaADZYKman9w
            7ZqmxchBlKFnJDMYPv4ZUd7nQux2VvlG/1hzGcGFbdhI38i94Tdejw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T10:26:03Z"
    mac: ENC[AES256_GCM,data:3DWICX8hNLq7V7widjz7ZFZbK7QctO8eh66tcEr/NyaV9xXTRylqp6QU0qJEqTp/1gHTUx6eRC1KKO2yJswfs82M0K7j/hpV1mn0NrprMG5BZ31rmkAFK3HEwWhYj1GbXrmgiy+i1hZhZChXJyJH+7Pj0EgWGjTYMcd6lBZULqY=,iv:WKmSHqFwxDCC+Mt6NqQSsm0TaT2o4PKDCUgtjHmIniQ=,tag:Osuo2O5hGqB8+80qegqm7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
