# manifests/infrastructure/firefly-iii/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: firefly-iii
  namespace: flux-system
spec:
  interval: 1h
  url: https://firefly-iii.github.io/kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly-iii-system
spec:
  interval: 5m
  releaseName: firefly-iii
  chart:
    spec:
      chart: firefly-iii-stack
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
      version: "*"
  values:

    firefly-db:
      enabled: false
      storage:
        class: ssd-nvme-predator-gm7000

    firefly-iii:
      enabled: true
      config:
        env:
          DB_HOST: 10.107.7.12
          DB_PORT: "5432"
          DB_DATABASE: firefly
          TZ: Asia/kolkata
        envValueFrom:
          DB_USERNAME:
            secretKeyRef:
              name: cnpg-firefly-user
              key: username
          DB_PASSWORD:
            secretKeyRef:
              name: cnpg-firefly-user
              key: password
    importer:
      enabled: true
