# manifests/infrastructure/firefly-iii/tunnel-binding-ingress.yaml

apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
    name: firefly-tunnel-binding
    namespace: firefly-iii-system
subjects:
  - name: firefly-iii
    spec:
        fqdn: money.rvsharma.com
        protocol: http
# - name: firefly-iii-importer
#   spec:
#       fqdn: moneyimporter.rvsharma.com
#       protocol: http
# Update tunnelRef below to match your cluster tunnel name
# Example:
tunnelRef:
    kind: ClusterTunnel
    name: i1-1806-talos-proxmox-cluster-tunnel
