# HomeLab-Kubernetes/manifests/infrastructure/minio-system/pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-samsung-860-evo-1
spec:
  capacity:
    storage: 220Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/samsung_860_evo_1
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-samsung-860-evo-2
spec:
  capacity:
    storage: 220Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/samsung_860_evo_2
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-samsung-860-evo-1
  namespace: minio-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 220Gi
  volumeName: pv-samsung-860-evo-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-samsung-860-evo-2
  namespace: minio-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 220Gi
  volumeName: pv-samsung-860-evo-2
