# HomeLab-Kubernetes/manifests/infrastructure/minio-system/tunnel-binding-ingress.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: minio-tunnel-binding
  namespace: minio-system
subjects:
- name: minio-console
  spec:
    fqdn: minio.rvsharma.com
    # protocol: http
    # noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: i1-1806-talos-proxmox-cluster-tunnel
