# manifests/infrastructure/cloudflare-zero-trust-operator/cloudflare-zerotrust-accessgroup.yaml
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessGroup
metadata:
  name: i1-1806-cloudflare-zerotrust-accessgroup
  namespace: cloudflare-zero-trust-operator
  annotations:
    # (optional) default: "false"
    #   ensures that the resource isn't removed from cloudflare if the CR is deleted
    cloudflare.zelic.io/prevent-destroy: "true"
spec:
  name: i1-1806-cloudflare-zerotrust-accessgroup
  include:
  - country:
    - IN
  - ipRanges:
    - 49.36.144.184/32
  # - emails:
  #   - SharmaR0810@gmail.com
