# manifests/infrastructure/cloudflare-zero-trust-operator/cloudflare-access-application.yaml

apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: i1-1806-cloudflare-zerotrust-access-application
  namespace: cloudflare-zero-trust-operator
  annotations:
    # (optional) default: "false"
    #   ensures that the resource isn't removed from cloudflare if the CR is deleted
    cloudflare.zelic.io/prevent-destroy: "true"
spec:
  name: Ollama
  domain: ollama.rvsharma.com
  autoRedirectToIdentity: true
  type: self_hosted
  policies:
  - name: Allow Email
    decision: allow
    include:
    - accessGroups:
      - value: i1-1806-cloudflare-zerotrust-accessgroup
