# manifests/infrastructure/cloudflare-zero-trust-operator/cloudflare-zerotrust-application-ollama.yaml
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: i1-1806-cloudflare-zerotrust-access-ollama-application
  namespace: cloudflare-zero-trust-operator
  annotations:
    # (optional) default: "false"
    #   ensures that the resource isn't removed from cloudflare if the CR is deleted
    cloudflare.zelic.io/prevent-destroy: "true"
spec:
  name: Ollama
  domain: ollama.rvsharma.com
  autoRedirectToIdentity: false
  type: self_hosted
  policies:
  - name: Allow Ollama ST Group Access
    decision: non_identity
    include:
    - accessGroups:
      - valueFrom:
          name: i1-1806-cloudflare-zerotrust-st-accessgroup
          namespace: cloudflare-zero-trust-operator
