# manifests/infrastructure/cloudflare-zero-trust-operator/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml
  - cloudflare-zerotrust-application-ollama.yaml
  - cloudflare-zerotrust-accessgroup-ollama.yaml
  - cloudflare-zerotrust-service-token-ollama.yaml
  - cloudflare-zerotrust-application-kubedash.yaml
  - cloudflare-zerotrust-accessgroup-kubedash.yaml
