# manifests/infrastructure/cloudflare-zero-trust-operator/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml
  # - cloudflare-zerotrust-accessgroup-st.yaml # Global access group for service token policies
  - cloudflare-zerotrust-service-token-fireflyiii.yaml # Service token for Firefly
  - cloudflare-zerotrust-service-token-paperlessngx.yaml # Service token for N8N
  - cloudflare-zerotrust-application-kubedash.yaml
  - cloudflare-zerotrust-application-paperlessngx.yaml
  - cloudflare-zerotrust-application-fireflyiii.yaml
  # Telegram Ingress, Somehow doesn't work with the zero trust policy.
  #   - cloudflare-zerotrust-application-n8n.yaml
  #   - cloudflare-zerotrust-service-token-n8n.yaml # Service token for N8N

  # For some reason, the accessgroup are not visible for attachement in the application.
  #   - cloudflare-zerotrust-accessgroup-email.yaml # Global access group for email policies
