# manifests/infrastructure/cloudflare-zero-trust-operator/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- release.yaml
- cloudflare-zerotrust-service-token.yaml
- cloudflare-zerotrust-accessgroup.yaml
- cloudflare-zerotrust-application.yaml
