# manifests/infrastructure/uptime-kuma/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.irsigler.cloud
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      version: "*"
  values:
    image:
      repository: louislam/uptime-kuma
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"

    volume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      # If you want to use a storage class other than the default, uncomment this
      # line and define the storage class name
      # storageClassName:
      # Reuse your own pre-existing PVC.
      existingClaim: "uptime-kuma-pv"
