# manifests/infrastructure/uptime-kuma/tunnel-binding-ingress.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: uptime-kuma-tunnel-binding
  namespace: uptime-kuma
subjects:
- name: uptime-kuma
  spec:
    fqdn: uptime.rvsharma.com
    # protocol: http
    # noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: i1-1806-talos-proxmox-cluster-tunnel
