apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: uptime-kuma-tunnel-binding
  namespace: uptime-kuma
subjects:
- name: uptime-kuma
  spec:
    fqdn: uptime.rvsharma.com
