# manifests/infrastructure/cloudflare-operator-system/cloudflare-gitrepo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/adyanth/cloudflare-operator.git//config/default?ref=v0.13.1
  ref:
    branch: v0.13.1
