# manifests/infrastructure/cloudflare-operator-system/cloudflare-gitpath.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
    namespace: flux-system
  path: ./config/default
  targetNamespace: cloudflare-operator-system
