# manifests/infrastructure/cloudflare-operator-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-gitrepo.yaml
  - ClusterTunnel.yaml

# - Tunnel.yaml
# - https://github.com/adyanth/cloudflare-operator.git/config/default?ref=main
# NameSpace is not needed as it is already created, But needed for secret
#   - namespace.yaml
