# manifests/infrastructure/cloudflare-operator-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NameSpace is not needed as it is already created, But needed for secret
  #   - namespace.yaml
  - https://github.com/adyanth/cloudflare-operator.git//config/default?ref=v0.13.1
  - ClusterTunnel.yaml
