# HomeLab-Kubernetes/manifests/infrastructure/cloudflare-operator-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cloudflare-gitrepo.yaml
- ClusterTunnel.yaml

# images:
# - name: cloudflare/cloudflared
#   newTag: 2025.2.1

# patchesStrategicMerge:
#   - update-cloudflared-image.yaml
