# HomeLab-Kubernetes/manifests/infrastructure/n8n/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- release.yaml
- tunnel-binding-ingress.yaml
- tools/k8s-Agent-SA.yaml

patches:
- target:
    kind: Deployment
    name: n8n
  patch: |-
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: k8s-agent-sa
