# manifests/infrastructure/n8n/release.yaml

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 1h
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: "1.0.10"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n-system
spec:
  interval: 5m
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: n8n
    namespace: flux-system
  values:
    _shared_config:
      hostname: &hostname n8n.rvsharma.com
      url: &url https://n8n.rvsharma.com
    image:
      repository: naskio/n8n-python
      pullPolicy: IfNotPresent
      tag: "1.104.0"
    main:
      extraEnv: &extraEnv
        N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:
          value: "true"
        N8N_RUNNERS_ENABLED:
          value: "true"
        N8N_PORT:
          value: "5678"
        N8N_PROTOCOL:
          value: "http"
        N8N_LOG_LEVEL:
          value: "info"
        OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS:
          value: "true"
        DB_POSTGRESDB_USER:
          valueFrom:
            secretKeyRef:
              name: cnpg-n8n-user
              key: username
              namespace: cnpg-system
        DB_POSTGRESDB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: cnpg-n8n-user
              key: password
              namespace: cnpg-system
        N8N_ENCRYPTION_KEY:
          valueFrom:
            secretKeyRef:
              name: n8n-encryption-key
              key: encryption_key
              namespace: n8n-system
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      persistence:
        enabled: true
        size: 20Gi
        storageClass: ssd-nvme-predator-gm7000
      config:
        webhook_url: *url
        executions_mode: queue
        n8n:
          license:
            activation:
              key:
                valueFrom:
                  secretKeyRef:
                    name: n8n-license
                    key: license_key
                    namespace: n8n-system
          port: 5678
          editor_base_url: *url
        db:
          type: postgresdb
          postgresdb:
            host: pg-n8n-cluster-rw.cnpg-system.svc.cluster.local
            port: 5432
            database: postgresql_n8n_pgsql
        queue:
          health:
            check:
              active: true
          bull:
            redis:
              host: redis-n8n-cluster.cnrds-system.svc.cluster.local
              port: 6379
      replicaCount: 1
    worker:
      enabled: true
      replicaCount: 1
      concurrency: 10
      extraEnv: *extraEnv
      persistence:
        enabled: true
        size: 20Gi
        storageClass: ssd-nvme-predator-gm7000
      # LifeCycle Does't work
      # podSecurityContext:
      #   runAsNonRoot: false
      #   runAsUser: 0
      #   runAsGroup: 0
      #   fsGroup: 0
      # lifecycle:
      #   postStart:
      #     exec:
      #       command: [ "/bin/sh", "-c", "apk add --no-cache python3 py3-pip && pip3 install pandas" ]
    webhook:
      enabled: true
      extraEnv: *extraEnv
