# HomeLab-Kubernetes/manifests/cluster/flux-system/cloudflare-operator-remote.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudflare-operator-remote
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator # Refers to the remote GitRepository
    namespace: flux-system
  path: ./config/default # Path in the remote repository
  targetNamespace: cloudflare-operator-system
