# HomeLab-Kubernetes/manifests/cluster/flux-system/cloudflare-operator-system.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/infrastructure/cloudflare-operator-system
  targetNamespace: cloudflare-operator-system
