# HomeLab-Kubernetes/manifests/cluster/flux-system/cloudflare-operator-system.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/infrastructure/cloudflare-operator-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: cloudflare-operator-system
  timeout: 2m
