# manifests/cluster/flux-system/control-plane-ingress.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: control-plane-ingress
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/control-plane-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
