# manifests/cluster/flux-system/freshrss.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: freshrss
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/FreshRss
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m0s
