# HomeLab-Kubernetes/manifests/cluster/flux-system/immich-system.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/immich-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
