# HomeLab-Kubernetes/manifests/cluster/flux-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cilium.yaml
- secrets.yaml
- cloudflare-operator-system.yaml # For NS and Secrets.
- cloudflare-operator-remote.yaml # For applying Remote Kustomization.
- dashboard.yaml
- rook-ceph.yaml
- cloudnative-pg.yaml

# Not used resources
# - ingress.yaml
# - local-path-provisioner.yaml
