# HomeLab-Kubernetes/manifests/cluster/flux-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cilium.yaml
- rook-ceph.yaml

# - secrets.yaml
# - cloudflare-operator-system.yaml # For NS and Secrets.
# - cloudflare-operator-remote.yaml # For applying Remote Kustomization.
# - dashboard.yaml
# - local-path-provisioner.yaml
# - cloudnative-pg.yaml
# - redis-operator.yaml
# - paperless-system.yaml
# - immich-system.yaml

# Not used resources
# - ingress.yaml #Deprecated in favour of Tunnel
