# HomeLab-Kubernetes/manifests/cluster/flux-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cilium.yaml
- local-path-provisioner.yaml
- secrets.yaml
- cloudflare-operator-remote.yaml
- cloudflare-operator-system.yaml
- redis-operator.yaml
- cloudnative-pg.yaml
- paperless-system.yaml
- immich-system.yaml

# - dashboard.yaml


# Not used resources, Only For Refrences in case Somone Wants to use it.
# - rook-ceph.yaml
# - ingress.yaml #Deprecated in favour of Tunnel
