# HomeLab-Kubernetes/manifests/cluster/flux-system/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cilium.yaml
- secrets.yaml

# - ingress.yaml
# - dashboard.yaml
