# HomeLab-Kubernetes/manifests/cluster/flux-system/local-path-provisioner.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-storage
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/infrastructure/local-path-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
