# manifests/cluster/flux-system/mcp-servers.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: mcp-servers
    namespace: flux-system
spec:
    interval: 5m
    path: ./manifests/infrastructure/mcp-servers/
    prune: true
    force: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    targetNamespace: mcp-servers
