# HomeLab-Kubernetes/manifests/cluster/flux-system/minio-system.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
