# manifests/cluster/flux-system/n8n.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: n8n-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/n8n
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
