# manifests/cluster/flux-system/nvidia.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/nvidia
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
