# manifests/cluster/flux-system/ollama.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/ollama
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
