# manifests/cluster/flux-system/openwebui.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openwebui
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/openwebui
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
