# HomeLab-Kubernetes/manifests/cluster/flux-system/paperless-system.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperlessngx
  namespace: paperless-system
spec:
  interval: 10m
  path: ./manifests/infrastructure/paperless-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
