# HomeLab-Kubernetes/manifests/cluster/flux-system/redis-operator.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/infrastructure/redis-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
