# manifests/infrastructure/openwebui/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openwebui
  labels:
    app: openwebui
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
