apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: openwebui-tunnel-binding
  namespace: openwebui
subjects:
- name: open-webui
  spec:
    fqdn: chat.rvsharma.com
