# HomeLab-Kubernetes/manifests/infrastructure/reflector/reflector.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack
  namespace: cert-manager
spec:
  interval: 5m
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: "<7.1.2888"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: cert-manager
      interval: 1m
  targetNamespace: cert-manager
