# HomeLab-Kubernetes/manifests/infrastructure/secrets/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudflare/tunnel-secret.yaml
- docker/docker-hub.yaml
- cloudnative-cnpg/r2-backup-restore-secret.yaml
- cloudnative-cnpg/pg-paperless-cluster-secrets.yaml
- cloudnative-cnpg/pg-immich-cluster-secrets.yaml
- paperless-system/pre-consumption-secrets.yaml
- paperless-system/postgresql-user.yaml
- paperless-system/paperless-socialaccount-providers-secret.yaml
- immich-system/postgresql-user.yaml
# - minio-system/minio-user.yamlx

# - cloudflare/cert-manager-cloudflare-secret.yaml
