# manifests/infrastructure/secrets/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- docker/docker-hub.yaml
- cloudflare/tunnel-secret.yaml
- cloudflare/zero-trust-secret.yaml
- cloudnative-cnpg/r2-backup-restore-secret.yaml
- cloudnative-cnpg/pg-paperless-cluster-secrets.yaml
- cloudnative-cnpg/pg-immich-cluster-secrets.yaml
- cloudnative-cnpg/pg-n8n-cluster-secrets.yaml
- cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
- cloudnative-cnpg/pg-openlit-cluster-secrets.yaml
- cloudnative-cnpg/pg-freshrss-cluster-secrets.yaml
- paperless-system/pre-consumption-secrets.yaml
- paperless-system/postgresql-user.yaml
- paperless-system/paperless-socialaccount-providers-secret.yaml
- paperless-system/paperless-gmail-auth.yaml
- immich-system/postgresql-user.yaml
- openwebui/openwebui-google-auth.yaml
- n8n-system/enc_key.yaml
- n8n-system/n8n-license-secret.yaml
- mcp-servers/fireflyiii.yaml
  # - cloudflare/cert-manager-cloudflare-secret.yaml
  # - minio-system/minio-user.yaml
