# HomeLab-Kubernetes/manifests/infrastructure/secrets/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - cloudflare/cert-manager-cloudflare-secret.yaml
- cloudflare/tunnel-secret.yaml
- docker/docker-hub.yaml
