# manifests/infrastructure/secrets/namespace.yaml

kind: Namespace
apiVersion: v1
metadata:
    name: secrets
    labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
