# HomeLab-Kubernetes/manifests/infrastructure/n8n/tools/k8s-Agent-SA.yaml
# A generic, multi-purpose ServiceAccount for Kubernetes automation agents.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-agent-sa
  namespace: n8n-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-agent-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "apps" ]
  resources: [ "replicasets" ]
  verbs: [ "get" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments", "daemonsets", "statefulsets" ]
  verbs: [ "get", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-agent-role
subjects:
- kind: ServiceAccount
  name: k8s-agent-sa
  namespace: n8n-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n-system
spec:
  interval: 5m
  values:
    serviceAccount:
      name: k8s-agent-sa
