# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- release.yaml
- local-path-config.yaml
