# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    app: local-path-provisioner
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
