# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: c7n
  namespace: flux-system
spec:
  url: https://openchart.choerodon.com.cn/choerodon/c7n
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-ssd-nvme-predator-gm7000
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: ssd-nvme-predator-gm7000
      defaultClass: true
      reclaimPolicy: Delete
    rbac:
      create: true
    nodePathMap:
    - node: "i1-1806-talos-worker01"
      paths:
      - "/var/mnt/ssd_nvme_predator_GM7000"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-ssd-sata-samsung-860-evo-1
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: ssd-sata-samsung-860-evo-1
      defaultClass: false
      reclaimPolicy: Delete
    rbac:
      create: true
    nodePathMap:
    - node: "i1-1806-talos-worker01"
      paths:
      - "/var/mnt/ssd_sata_samsung_860_evo_1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-ssd-sata-samsung-860-evo-2
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: ssd-sata-samsung-860-evo-2
      defaultClass: false
      reclaimPolicy: Delete
    rbac:
      create: true
    nodePathMap:
    - node: "i1-1806-talos-worker01"
      paths:
      - "/var/mnt/ssd_sata_samsung_860_evo_2"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-ssd-data-lexar-120gb-1
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: ssd-data-lexar-120gb-1
      defaultClass: false
      reclaimPolicy: Delete
    rbac:
      create: true
    nodePathMap:
    - node: "i1-1806-talos-worker01"
      paths:
      - "/var/mnt/ssd_data_Lexar_120GB_1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-ssd-data-lexar-120gb-2
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: ssd-data-lexar-120gb-2
      defaultClass: false
      reclaimPolicy: Delete
    rbac:
      create: true
    nodePathMap:
    - node: "i1-1806-talos-worker01"
      paths:
      - "/var/mnt/ssd_data_Lexar_120GB_2"
