# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: c7n
  namespace: flux-system
spec:
  url: https://openchart.choerodon.com.cn/choerodon/c7n
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: true
    rbac:
      create: true
    config:
      name: local-path-config # Reference the ConfigMap with storage class configurations
      namespace: local-path-storage
    storageClasses:
    - name: local-path
      defaultClass: true
      reclaimPolicy: Retain
    - name: minio-backup
      defaultClass: false
      reclaimPolicy: Retain
