# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: c7n
  namespace: flux-system
spec:
  url: https://openchart.choerodon.com.cn/choerodon/c7n
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: c7n
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: true
    rbac:
      create: true
    nodePathMap:
    - node: "DEFAULT_PATH_FOR_NON_LISTED_NODES"
      paths:
      - "/opt/local-path-provisioner"
