# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/storageclasses.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio_samsung_860_evo_1
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /var/samsung_860_evo_1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio_samsung_860_evo_2
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /var/samsung_860_evo_2
