# HomeLab-Kubernetes/manifests/infrastructure/local-path-provisioner/storageclasses.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd_nvme_predator_GM7000
annotations:
  storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /var/ssd_nvme_predator_GM7000
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd_sata_samsung_860_evo_1
annotations:
  storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /var/ssd_sata_samsung_860_evo_1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd_sata_samsung_860_evo_2
annotations:
  storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /var/ssd_sata_samsung_860_evo_2
