# manifests/infrastructure/jellyfin/tunnel-binding-ingress.yaml
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: jellyfin-tunnel-binding
  namespace: jellyfin
subjects:
- name: jellyfin
  spec:
    fqdn: tv.rvsharma.com
    # protocol: http
    # noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: i1-1806-talos-proxmox-cluster-tunnel
