# 271_Labs/HomeLab-Kubernetes/manifests/infrastructure/plex-system/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 1h
  url: https://plexinc.github.io/pms-docker/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-media-server
  namespace: plex-system
spec:
  interval: 5m
  chart:
    spec:
      chart: plex-media-server
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
      version: 0.6.0
  values:
    pms:
      storageClassName: ssd-sata-samsung-860-evo-2
    extraVolumes:
    - name: media
      hostPath:
        type: Directory
        path: "/var/mnt/ssd_data_Lexar_120GB_2/plex/media"
    - name: transcode
      hostPath:
        type: Directory
        Path: "/var/mnt/ssd_data_Lexar_120GB_2/plex/transcode"
    # Environment Variables
    env:
      PLEX_CLAIM: "claim-y6D2WEjWaA7BixzvxqLK"
      PLEX_UID: "1000"
      PLEX_GID: "1000"

    # Service Configuration
    service:
      type: NodePort
      ports:
        web:
          port: 32400
          targetPort: 32400
        dlna:
          port: 1900
          targetPort: 1900

    # Security Context
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - "ALL"
      seccompProfile:
        type: RuntimeDefault

    hostNetwork: true

    # Update Strategy
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
