# HomeLab-Kubernetes/manifests/infrastructure/immich-system/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ssd-nvme-predator-gm7000
