apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: immich-tunnel-binding
  namespace: immich-system
subjects:
- name: immich-server
  spec:
    fqdn: photo.rvsharma.com
