# HomeLab-Kubernetes/manifests/infrastructure/ceph-cluster/ceph-diskwipe.yaml
# Do not Run this, Disk will be Wiped.
apiVersion: v1
kind: Pod
metadata:
  name: disk-wiper
  namespace: rook-ceph
spec:
  restartPolicy: Never
  containers:
  - name: disk-wiper
    image: busybox
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    command:
    - "/bin/sh"
    - "-c"
    - |
      echo "Wiping disks vda, vdb, and vdc..."
      dd if=/dev/zero of=/dev/vda bs=1M count=100 || true
      dd if=/dev/zero of=/dev/vdb bs=1M count=100 || true
      dd if=/dev/zero of=/dev/vdc bs=1M count=100 || true
      echo "Disk wipe completed."
