# HomeLab-Kubernetes/manifests/infrastructure/ceph-cluster/cluster.yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.0
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    modules:
    - name: rook
      enabled: true
  dashboard:
    enabled: true
  monitoring:
    enabled: false
  network:
    provider: host
  storage:
    useAllNodes: true
    useAllDevices: true
    # nodes:
    # - name: I1-1806-Talos-Worker01
    #   devices:
    #   - name: vda
    #   - name: vdb
    #   - name: vdc
    #   config:
    #     osdsPerDevice: "1"
    #     storeType: bluestore
  placement:
    all:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
