# HomeLab-Kubernetes/manifests/infrastructure/secrets/minio-system/minio-user.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio-system
type: Opaque
stringData:
  rootUser: sharmar0810
  rootPassword: xYVwGiZCU7qFm1
