# manifests/infrastructure/secrets/openwebui/openwebui-google-auth.yaml
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-google-auth
    namespace: openwebui
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:AhGtgsJ4TfojX/EBAn2+pXb7L5mpR5TDcKVeyKXQE7ZVLI4R6ACebS93+pfkwgAYsMxF3Mqyk2ET7b65+LmeU+GsqiIxi/M7,iv:WJWjVAi/qgOtZ26IKW1qHB78x8EcDj+8LVaTqkzwun8=,tag:3qeDNYw+OHaNIi0LYIGJwQ==,type:str]
    client_secret: ENC[AES256_GCM,data:Y4dyI5rPNjjSa8ZSmhO+ngxpszhL7y7XQcYHnrkmMBZw35I=,iv:s67JjPEslf+NC7bRSWek5wm+bOjhkygyBrKd+yDsUYc=,tag:36PuTCWUp32a9ENwJPEa3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbURlbVVDcFNjaFBpUWZU
            c29QaTdFNkkzZmFKQmZBbTVMWXlrV2JjL2prCnJ5eTJzZ3djYUU4V2NiMGttU2g5
            cGhwcnhXQTZESFFaYnFvU1dZaFNkTTQKLS0tIGFzOWp5UU9jM1A4Nld6NHVvS0V1
            ZGpkV1F2WU5SVGZtWUxKVUZQa09XOGsK0VpacPbqLmUoPQPOYsqG1C1u9hri93GO
            MWUe12GJPtca7uXu/egdhDAW3vL1PJZO8Zd3gtw5yc7E1ZER1stbgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T12:33:41Z"
    mac: ENC[AES256_GCM,data:O3oNCEbEscSLnqaF5u83d1RydpgpaKDgICRTtdyu9VCMnfE9vEpPFZ3Pv1h4dF62DkTF/xXj3SBl51CZasIFDxLUnxR4QaeJtxvYewfso9YWFLgQjsKX8jT9pP26IPjcP8VZgvjyOSdgAwoUv4UuzzGb4zg9RCaWvKHT3d5BLX0=,iv:utHCDYpnRkidEBtHoLpYnIteGTNdMJoSuuH3skgh74Y=,tag:gSypBjyv9tDUtvz6j+tUrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
