# HomeLab-Kubernetes/manifests/infrastructure/cert-manager/cloudflare-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:DSLNWbtNGW3bJjngdbxbGQ4k710Ih8wQ34hqWExIqokthVcfPhQTxw==,iv:RG+gjbQxdcDkiv4Hy0rHKbxeZRoxb+eRgtFyhtJ7SSs=,tag:ApSeqUC7R2dBYqY1DzVc2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSVVwRXhGeXBTb1hMWEFW
            NDllajhDVWlKQnVxV2k1MnZkN0IyMzhSTlVFCmJpN2NrOHlBaFcwVG5mZnhKdjlI
            bWprU1lVZVMyZTh4K0dWRU50ellTTjQKLS0tIGxOUzRzOXdsb0M3RDJIdXNRUFla
            NGdUMWw1Q3hjdHBENEJsNVl1YTFmUXcKUufc/BvE9ZKhvCtc4zAsqPQ8p8/PSX3T
            eED6wHP8p1yORdOzgX7lLth+KxM9uCbQk4hv+9ecchrQ0EY7QfTWdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T20:53:47Z"
    mac: ENC[AES256_GCM,data:CtJd8Aq/IvarabLo0nnCkbzK/r3ECf9LHusyMNk0E9KOPeZRDmLEFYiL+ml0tdwPkwRPX1OPn9pkLc495koqhrtZmwTAlh+7FuE9+x6jfEfdwSRgpX+BV5/3wHVLkGTrmWMmL4uiGaEmuPwg0oYE04dPhG5J6Wj0sKuKfNFTN2c=,iv:qWOAoEEX46RAlFxP5FHQj1DzU4g7GTYdME3TnEJn4wA=,tag:XyJE0KxXBlwquNyCiO12UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
