# manifests/infrastructure/cert-manager/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager.yaml
  - cloudflare-certificate.yaml
  - cloudflare-certificate-issuer.yaml
