apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:WsM601uuaM5CKiJxJIgq1TkV4DfYb/wd7aei4c4oKWH9WThtEI1lIe2FUqdEVESW1iAZrzyJZkx9oLTNf6KwQMbE8z0Co8e56gw/NGa+SlwR3qX5+HlZQmWzSLaOXRWMa2BF8B5CJ4/FKxXC4fBmn0Hk48GFdr3l1z2kXHyMrXzEVt4RebA3nl90lCwepp05XOscdi74hw2/ANkWN6UdqUfyVGI9virDRjiP1XsC267uNneCDi7jQkVEAaU=,iv:KfA1n8YNdhvBnlBfAK5uWsx6R4qFFj052wjtjVcEwWg=,tag:2961yLHLFX6odnW/Bg2trg==,type:str]
kind: Secret
metadata:
    name: docker-hub-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
      - recipient: age1g9f5g9a02tc60zhqezv3uhkup6g309ygnpk7k8yf8hys48gcw5zqghf0zx
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMjA5cTQ2T2sxTTJzLzMw
            c2IxbWZMQk9wWEIxbGRzaGRLdkRjRlYzVmhjClc4U0Q5ZTl3c0NxSWRLeFAxbm9h
            VFZ6aWZ2V1NPQnNPcS9YZG1pS2czYTAKLS0tIDZRR0I1TGd1bWR4YUhBdkJCdjNv
            Z2p0UTRVekQzYTJ5anlFM3k1VWtvZlkKrW4iZefj8ehEggF1mK1JGb8EfgEZudYr
            z4cm8c5pDTla01XgY8C0ZXO6DjbOaj1L6ukvzzxNg2B5pVQM8QrkVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T14:07:54Z"
    mac: ENC[AES256_GCM,data:mVMsqS+m/sMB5kxA+bCLxR6cMzL7JIkegNdI57Fatz6LfVdDYrZg+Wry9ybTlkq4cP7Nd0/WW5bvFomhJJ5GaFdQrzORFEemw/oSI3VtQXh69IseNIuNnNOhPH1hCMwPGUEQbVSpha55wzenrHoq/EEdiX+FfSX6TczcLn5ejF4=,iv:4PNgdwyWMUK2XxzsdP/Xy4+/ZuZzYdBfOwjq/zB94FY=,tag:pyIB0XIUYRfy6mlVnD1mxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
