apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hzut78Lz/7dHH63uk77UyRrcquzmfShaEF2XDRj+wvkpD30/J46wPGykRXT1nRP1G37+eRFxMk84u+GkiM2SneQ9FoWRkXsqjH5wVF7APgENpX1NmsjOWhhk/p5n/y5Y4KDgzL2d9sgFJALVAZCOU8a8mSZnBzsDDGPgNE9b+GFKY1W0TgSCY0bxT9c3K57R7N+P7t1N7ZgJdT+tmulbNCeSHSpDTbnIYbP8KQYsHO1w37HYMIL/xGN0yek=,iv:xtURuRYUCEVirgsCZXQh7stXM8NUkp5xYcdp387CtDY=,tag:pW/w0g+fxUODSVOVnULV0A==,type:str]
kind: Secret
metadata:
    name: docker-hub-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9f5g9a02tc60zhqezv3uhkup6g309ygnpk7k8yf8hys48gcw5zqghf0zx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cUQxTUNMaUZCOEZ2TEhU
            WnRRZHRCdWpTVjFQS0lDaE1KN2dsRkNFWHk4CmlmTXR0Z0Y0MGpGQzFjV1o1dFQ1
            cmdCY1BPZlZqYWNtNFA5YWV5N3FxMDAKLS0tIFpzaGZwclBlVHBPeFdXOFdaSmla
            RnMwb1RBbHdTY2h5VjBES2FnVE5WbVUKJQNqypkIOkMctZOx4zuUSHJAoyz2+//+
            BAWe4tpH9ofOWfj4IOy0EvyQEh3PlhYVqYMM7egUa4RZphLyi7OfhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T11:27:02Z"
    mac: ENC[AES256_GCM,data:tTd22LRfVdBGjiLeHlNQWfeIt+RnbdfQBEWM4Fcpt1ZaiXn8I4gsM3Jkye7K7rd/aERh1TC8IiLhpOACEq/xDknsqHBUgS1hSQ9by8otKg94GWvFCQl4VmchDl3h1S22jevo47za/ql9+iW44WaeJRiHpCmvXN8VCQPXnPmMA/0=,iv:l8DAMoRWXkVxDD88D26tL78PquFNK/N470fw4DaJ8vo=,tag:eKQ2Ssobhrn6Zew3kRsTXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
