# manifests/infrastructure/nvidia-device-plugin/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
