# manifests/infrastructure/nvidia/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvdp
  namespace: flux-system
spec:
  interval: 30m
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia
spec:
  interval: 5m
  timeout: 3m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    runtimeClassName: nvidia
    config:
      name: mps-config
      data:
        any: |-
          version: v1
          flags:
            migStrategy: none
          sharing:
            mps:
              resources:
              - name: nvidia.com/gpu
                replicas: 10
    # the mps-config ConfigMap is missing
    # kubectl create configmap mps-config -n nvidia --from-literal=any="version: v1
    # flags:
    #   migStrategy: none
    # sharing:
    #   mps:
    #     resources:
    #     - name: nvidia.com/gpu
    #       replicas: 10
