# manifests/infrastructure/nvidia/test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-rtx-4090-gpu
spec:
  runtimeClassName: nvidia
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: [ "nvidia-smi" ]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
