# HomeLab-Kubernetes/manifests/infrastructure/FreshRss/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: christianhuth
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.christianhuth.de
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: freshrss-system
spec:
  interval: 5m
  chart:
    spec:
      chart: freshrss
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: christianhuth
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: freshrss/freshrss
    tag: "1.26.3"
      pullPolicy: Always
      type: alpine
    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false

    persistence:
      enabled: true
      storageClass: "ssd-nvme-predator-gm7000"
      accessMode: ReadWriteOnce
      size: 1Gi

    env:
    - name: TZ
      value: "Asia/Calcutta"
    - name: CRON_MIN
      value: "*/20"
    - name: DB_HOST
      value: "pg-freshrss-cluster-rw.cnpg-system.svc"
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: "freshrss"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: cnpg-freshrss-user
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: cnpg-freshrss-user
          key: password
    - name: DB_TYPE
      value: "pgsql"
