# HomeLab-Kubernetes/manifests/infrastructure/FreshRss/release.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: christianhuth
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.christianhuth.de
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: freshrss-system
spec:
  interval: 5m
  chart:
    spec:
      chart: freshrss
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: christianhuth
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: freshrss/freshrss
      tag: "1.26.3"
      pullPolicy: Always
      type: alpine
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    freshrss:
      baseUrl: "https://freshrss.rvsharma.com"
      cronjob:
        type: internal
        minutes: "1,31"
      database:
        type: postgresql
      environment: production
      initialization:
        # -- Use Auto-install for initialization. Make sure to set this to false once the initialization is done.
        enabled: false
        # admin:
        #   apiPassword: ""
        #   email: ""
        #   password: ""
        #   username: ""
        apiEnabled: true
        language: en
      persistence:
        enabled: true
        data:
          enabled: true
          storageClass: "ssd-nvme-predator-gm7000"
          size: 5Gi
          accessModes:
          - ReadWriteOnce
        extensions:
          enabled: true
          accessModes:
          - ReadWriteOnce
          size: 5Gi
          storageClass: "ssd-nvme-predator-gm7000"
    timezone: "Asia/Calcutta"
    externalPostgresql:
      auth:
        # -- Name of the database to use
        database: "freshrss"
        # -- Name of existing secret to use for PostgreSQL credentials
        existingSecret: "cnpg-freshrss-user"
        # -- Name of the user to use (key in the secret)
        username: "postgresql_freshrss_pgsql"
        # -- Key in the secret containing the password
        userPasswordKey: password
      hostname: "pg-freshrss-cluster-rw.cnpg-system.svc"
      # -- Port used to connect to PostgreSQL database
      port: 5432
