# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:1ruYnKGPYcDcJLTG,iv:bee6FmMnRfUJMIJkWJyqRx4+OQpBjYGQ4B62grYmwKM=,tag:cxN+63o3SQbQhPnWWfNWXg==,type:str]
    password: ENC[AES256_GCM,data:2UOR42znHXwMgbOA74Wr8z/HbGx1DkWJ,iv:ogz6HkEiWg2dEnUghglbp676Ohqj45hqPo7DsqNglns=,tag:x1HqwT2ZYRDekmRgLHCKkw==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ0YxeTVzU3IxZExsVGk5
            ZzYxKzJlekZ4ODNiZ1FNeHBwdWlaZFNMdFJzCmJUZWZOMGhEUk1wWlhMci9oUElM
            bGxwbG11OFRQdXJLM1BuOVc5WXNmcTQKLS0tIFpJRUlDWExxcmh3WmRNNncyV1FR
            aERlYzdiQi9remtxdk5KSXFmUkltRWMKMWVJ137dttHjIwEDolJ1tvzD+hO0he26
            7s6KEZYSZ2z8SkXutgUHnqWgKaz6wsY0EI1zMLuUl0p31Y7NgIlRUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:22:17Z"
    mac: ENC[AES256_GCM,data:nnRD3GbzG8UiSAvcVWobnhjQEj7Q5ThgipJLgRrExS9hdU61Pg/TdghVji9JxaKnLitjn34fsJ0PvtENGIxB65c8gehPkpbkW3ce73sEEqFuSL2FTa/4rDlcRaFCo9OBtPUlXUZbaqSH+51l92X4Lj9ITcnyW+DYXnhDNkpLTDE=,iv:ANK6iFNLvKzzCz+XhTICttfgKSdu3AKqg3kwZHe8pGE=,tag:j/+3tFZrR5SmtFOPI/ucIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:TjEnPoEVV+qvx5BtHjHwhLH0+9tAN5nViykE6LUucGg=,iv:6qRJOg4o3mUcIsIs/ANkl6+rA20rdR0JFPjps+RLND0=,tag:BV2VL/yEy30YQNAOlMefxg==,type:str]
    password: ENC[AES256_GCM,data:2mxWSVVTRQZ9gXhrTLLrmws+aTyW6W0yDz2SNYrx5sEJzuNfACQ4yaJEaao=,iv:IDUZ147LR64lO6JCZkhJB7vXIZMYi+dOyWtQ2CdE8IQ=,tag:JVH+Vag4fzY6ehnfsElclA==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ0YxeTVzU3IxZExsVGk5
            ZzYxKzJlekZ4ODNiZ1FNeHBwdWlaZFNMdFJzCmJUZWZOMGhEUk1wWlhMci9oUElM
            bGxwbG11OFRQdXJLM1BuOVc5WXNmcTQKLS0tIFpJRUlDWExxcmh3WmRNNncyV1FR
            aERlYzdiQi9remtxdk5KSXFmUkltRWMKMWVJ137dttHjIwEDolJ1tvzD+hO0he26
            7s6KEZYSZ2z8SkXutgUHnqWgKaz6wsY0EI1zMLuUl0p31Y7NgIlRUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:22:17Z"
    mac: ENC[AES256_GCM,data:nnRD3GbzG8UiSAvcVWobnhjQEj7Q5ThgipJLgRrExS9hdU61Pg/TdghVji9JxaKnLitjn34fsJ0PvtENGIxB65c8gehPkpbkW3ce73sEEqFuSL2FTa/4rDlcRaFCo9OBtPUlXUZbaqSH+51l92X4Lj9ITcnyW+DYXnhDNkpLTDE=,iv:ANK6iFNLvKzzCz+XhTICttfgKSdu3AKqg3kwZHe8pGE=,tag:j/+3tFZrR5SmtFOPI/ucIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: firefly-iii-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:vbQRKWE3bIrnpMPNLQSgG8vZ31MuiCUIK6RlydiGF94=,iv:3o2cetOAg/or2uOmc1Po7DFOZOFkdI/utCUoQZ+XZWY=,tag:05HZSlfHuFGnRjMNpQZrhA==,type:str]
    password: ENC[AES256_GCM,data:IVgjIF/nnZs6mq74dx5fxW/0nijZJt1YC30OExO8Bt1w7EdtUd2QovtX8cM=,iv:KvK4IU2uZx9Ca8ZAjmHw/zAy4OBRGsR5w6zBnU+YtEQ=,tag:MRk3d/kuhWNvjUfPCGbA1Q==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ0YxeTVzU3IxZExsVGk5
            ZzYxKzJlekZ4ODNiZ1FNeHBwdWlaZFNMdFJzCmJUZWZOMGhEUk1wWlhMci9oUElM
            bGxwbG11OFRQdXJLM1BuOVc5WXNmcTQKLS0tIFpJRUlDWExxcmh3WmRNNncyV1FR
            aERlYzdiQi9remtxdk5KSXFmUkltRWMKMWVJ137dttHjIwEDolJ1tvzD+hO0he26
            7s6KEZYSZ2z8SkXutgUHnqWgKaz6wsY0EI1zMLuUl0p31Y7NgIlRUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:22:17Z"
    mac: ENC[AES256_GCM,data:nnRD3GbzG8UiSAvcVWobnhjQEj7Q5ThgipJLgRrExS9hdU61Pg/TdghVji9JxaKnLitjn34fsJ0PvtENGIxB65c8gehPkpbkW3ce73sEEqFuSL2FTa/4rDlcRaFCo9OBtPUlXUZbaqSH+51l92X4Lj9ITcnyW+DYXnhDNkpLTDE=,iv:ANK6iFNLvKzzCz+XhTICttfgKSdu3AKqg3kwZHe8pGE=,tag:j/+3tFZrR5SmtFOPI/ucIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
