# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: cG9zdGdyZXM=
    password: cG9zdGdyZXNfc3VwZXJ1c2Vy
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: cG9zdGdyZXNxbF9maXJlZmx5X3Bnc3Fs
    password: cG9zdGdyZXNxbF9maXJlZmx5X3Bnc3FsX3NlY3JldA==
