# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
<<<<<<< HEAD
    username: ENC[AES256_GCM,data:PKK8BUKWyqEGF7OI,iv:aY8w1L/huSw7NdcAfbFBk8iqj1BTTRAK/uy3SMKxKh4=,tag:RG75YHN+XB13Cn4sowVKew==,type:str]
    password: ENC[AES256_GCM,data:hHBBIcylKCEbyQ6rvgNeZzuNUCTZLmPx,iv:H4E2/iSs/mXc/rWkO63rLXuUwST8WAd1SgZ2dvtI10A=,tag:QP/F/BcOKAc5CHvjDPlajw==,type:str]
=======
    username: ENC[AES256_GCM,data:MYnYm1pkdLgb9KFn,iv:zpi4cOBbWRBQ35jElzMjaxBNHymEhNh6bD7fRridiMg=,tag:2Byq/T/nyfngaKJ+Pb6q6g==,type:str]
    password: ENC[AES256_GCM,data:bFCp1bQf7ZW+eEPhGaV12HsbmU5U9S6I,iv:9vEhM+w96+ClZDxY+QUDtHAejRj7d04bZ9FgrzmTtCY=,tag:Fn2/00Dg3lejPCDnxRFeww==,type:str]
>>>>>>> 4329388 (firefly: Rename secrets to match Firefly naming convention)
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
<<<<<<< HEAD
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhxMFhaMlZOVkVxdHd1
            Y0h0am1MTkJBYUVlc2t5d0FtUk9Tb2x0bFNJClZTYWxaNURPTi9uVkJtVHhFVVg1
            V3BhQmp2QlFhd0U2RmhaVjFBeXhkR3MKLS0tIG1SVjJtZStVVzZycXA3TmhNS2xM
            UVd3NUM0clJPUkloV0pNYlo1TWE3NmMKJjwp8USlY3vs8TL+I6wLNAgJ0RWxiVMS
            yOvEYOddqObjvotq0ibg/RGlGJUl/ui9gtwegHZHBjtCuqtLL9Jnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T10:25:07Z"
    mac: ENC[AES256_GCM,data:EJKGv+mROJB8gV45HacNU3UH4ASQXMGvhrUOgJqiNVaWCWHgyqO/gDk96Fkmmqno96vBmVjyakKkvyVN0k2lXMYPQKXZNkiiWKmBX7yD01aGi7gjL2UQNnRPCb7H4X1kcy0Ujc58XJRb2VV3vlJPYS2dtY53kFudylJj7cE+wUQ=,iv:Xu0higgS/S8GxA34jV2Gcro895qM8VOBZ5426U0iCm8=,tag:kENSFF+FqyRa5/T7JWL+8Q==,type:str]
=======
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ1IxZzNGcDY4UCs5UnJT
            WDI2dmRWdXVMd1JjajErUElNcUYxeWMzZ0RzCmJXQ3hlODhtejc3V2JSQ2J5aG9M
            MVNmTURpVWxEZFVXc21GQWN0Z3dRak0KLS0tIDNqSFdlVWpkMDhxNTFLNGJhYUhI
            WUNmOFIraG9MTGp5bkx4QmM0SzQzNUUKF+NEoO3fn7seNiKOcBn5MWNqTYpdLCsW
            /ECHZhgU+l7+0G659NWKA3AI9wrBFg1KS6SlHLje5tQnUE1nICnT7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:14:10Z"
    mac: ENC[AES256_GCM,data:RU7aCJm5RMh2Db2M5qbE/Plva0hEWzZdZA1YAxsnyrXoJ5D/9FPcaAYhiyyhWFOU3yrbkE7kzRRyIR4g2veKXKrgJB3JmU4eQs0VlSN0yE+aNNOZhqyrOwfKfINHc2XOM2+EUFvHH/jrPdbcazAa3NoaE155Qk6WqNUQBceUyeo=,iv:ym6hL+z6MGtgD8h9mfH1pNDK0mMR9c+EiGVjLRWd1Iw=,tag:t6HjevPIw14Oz4Fy5dYO6A==,type:str]
>>>>>>> 4329388 (firefly: Rename secrets to match Firefly naming convention)
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
<<<<<<< HEAD
    username: ENC[AES256_GCM,data:i+7XpRqwE9MhEt/C6kXzKVHgcbohk5Uy1dwq8Ss7MtE=,iv:1Pw7Z/LVqwcryO9QaqMXAjaV4Wth03T+px4SLTPiL8k=,tag:lEiW9P5SQ/KOHx0etiorNA==,type:str]
    password: ENC[AES256_GCM,data:g/DN4BnQX+WwmZJhSA15J26s+u7HLNa+812366ZV/DHxNDWQiYtN7jG68wg=,iv:r3jSDWZlnVz9moDXBu0WvHlkQkXjbRkk+u40GWP4F3Y=,tag:OQIeuQrljjTTt84dV0fd3g==,type:str]
=======
    username: ENC[AES256_GCM,data:CqM/3fndqIGsMfwRmSFlzXuPJJwSgSvb16ByVmhqdPs=,iv:ukViFwgEjtl2wxRVowCwdILpNeFMSAEGGN4fx8lBy2g=,tag:Ow+LDaGCcSzBkicjAy36Nw==,type:str]
    password: ENC[AES256_GCM,data:wM8pLuL3XSkIUVUDMuWdtaQQbFst6U+7/kLQqtXrUqIqri34Cq1462qpPgw=,iv:nSx57frSXvmH8C1PuORMosBs/HTFWek3KGYZoM3TNbg=,tag:u6SEVLHaSCGfdla/7oNlTQ==,type:str]
>>>>>>> 4329388 (firefly: Rename secrets to match Firefly naming convention)
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
<<<<<<< HEAD
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhxMFhaMlZOVkVxdHd1
            Y0h0am1MTkJBYUVlc2t5d0FtUk9Tb2x0bFNJClZTYWxaNURPTi9uVkJtVHhFVVg1
            V3BhQmp2QlFhd0U2RmhaVjFBeXhkR3MKLS0tIG1SVjJtZStVVzZycXA3TmhNS2xM
            UVd3NUM0clJPUkloV0pNYlo1TWE3NmMKJjwp8USlY3vs8TL+I6wLNAgJ0RWxiVMS
            yOvEYOddqObjvotq0ibg/RGlGJUl/ui9gtwegHZHBjtCuqtLL9Jnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T10:25:07Z"
    mac: ENC[AES256_GCM,data:EJKGv+mROJB8gV45HacNU3UH4ASQXMGvhrUOgJqiNVaWCWHgyqO/gDk96Fkmmqno96vBmVjyakKkvyVN0k2lXMYPQKXZNkiiWKmBX7yD01aGi7gjL2UQNnRPCb7H4X1kcy0Ujc58XJRb2VV3vlJPYS2dtY53kFudylJj7cE+wUQ=,iv:Xu0higgS/S8GxA34jV2Gcro895qM8VOBZ5426U0iCm8=,tag:kENSFF+FqyRa5/T7JWL+8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
# Secret are namespaced scope in k8s
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: firefly-iii-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:iw5T7fhgGWLv8omBc+APko9+0PszoBSRL6BHoCb2yzg=,iv:GEThr4RFynCeVhFMHO3oOyM+9F2iD9w15+sEuSyhMho=,tag:99XaMKvXOqnPvNgY+5ekBA==,type:str]
    password: ENC[AES256_GCM,data:sAsgotKhiCd9pEuTgSbWD6GZ45oP9/Epf0j2DkM0TpORqSY7RgX3uLF3PhU=,iv:B15yYBb4wHcEInFNVYElr453DbxJC/Q7NLetYEVfhXQ=,tag:zGt3I3cpS5IVlOMNR90V9g==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhxMFhaMlZOVkVxdHd1
            Y0h0am1MTkJBYUVlc2t5d0FtUk9Tb2x0bFNJClZTYWxaNURPTi9uVkJtVHhFVVg1
            V3BhQmp2QlFhd0U2RmhaVjFBeXhkR3MKLS0tIG1SVjJtZStVVzZycXA3TmhNS2xM
            UVd3NUM0clJPUkloV0pNYlo1TWE3NmMKJjwp8USlY3vs8TL+I6wLNAgJ0RWxiVMS
            yOvEYOddqObjvotq0ibg/RGlGJUl/ui9gtwegHZHBjtCuqtLL9Jnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T10:25:07Z"
    mac: ENC[AES256_GCM,data:EJKGv+mROJB8gV45HacNU3UH4ASQXMGvhrUOgJqiNVaWCWHgyqO/gDk96Fkmmqno96vBmVjyakKkvyVN0k2lXMYPQKXZNkiiWKmBX7yD01aGi7gjL2UQNnRPCb7H4X1kcy0Ujc58XJRb2VV3vlJPYS2dtY53kFudylJj7cE+wUQ=,iv:Xu0higgS/S8GxA34jV2Gcro895qM8VOBZ5426U0iCm8=,tag:kENSFF+FqyRa5/T7JWL+8Q==,type:str]
=======
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ1IxZzNGcDY4UCs5UnJT
            WDI2dmRWdXVMd1JjajErUElNcUYxeWMzZ0RzCmJXQ3hlODhtejc3V2JSQ2J5aG9M
            MVNmTURpVWxEZFVXc21GQWN0Z3dRak0KLS0tIDNqSFdlVWpkMDhxNTFLNGJhYUhI
            WUNmOFIraG9MTGp5bkx4QmM0SzQzNUUKF+NEoO3fn7seNiKOcBn5MWNqTYpdLCsW
            /ECHZhgU+l7+0G659NWKA3AI9wrBFg1KS6SlHLje5tQnUE1nICnT7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:14:10Z"
    mac: ENC[AES256_GCM,data:RU7aCJm5RMh2Db2M5qbE/Plva0hEWzZdZA1YAxsnyrXoJ5D/9FPcaAYhiyyhWFOU3yrbkE7kzRRyIR4g2veKXKrgJB3JmU4eQs0VlSN0yE+aNNOZhqyrOwfKfINHc2XOM2+EUFvHH/jrPdbcazAa3NoaE155Qk6WqNUQBceUyeo=,iv:ym6hL+z6MGtgD8h9mfH1pNDK0mMR9c+EiGVjLRWd1Iw=,tag:t6HjevPIw14Oz4Fy5dYO6A==,type:str]
>>>>>>> 4329388 (firefly: Rename secrets to match Firefly naming convention)
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
