# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:tBc+boa/CEDBscf2,iv:IoCeONR1LI5zDOYcGYymWhs7YCXuM+bUTLTKao2P4NA=,tag:mGJneoS7L7t6y1RuHWZrjg==,type:str]
    password: ENC[AES256_GCM,data:2/ReoD+44DRu7Myilq85E2O3KOaM5n+M,iv:BnC8thr6WkQbcIvdxGBAAq/d+gwFCcCYslU4KSHtbOY=,tag:xWHxpx/L8IlSsSishzNLyA==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MWR2ZloxVFBkcXIvam9N
            OG5tVHNRT1YrMnFmelNjWUJRTXVIT1F5OWlvCk9ZQ0NYUkJpMFRaZlFxeGtDQ2cy
            UzU5Y3AvY3NCa2tsMzFzaFRFVmp5LzgKLS0tIG1CbktlT1ZqaTU4b3hVdS9FbnFB
            S1BtbWVQQXJDS1h5VzdiRW11WW52dm8KoL3ZE/TE0poOOOzjl8o7XP5y8ybAGowz
            KpLeOesx+RmiX1AO8YBjUFG3pRy5ABPLAFOo/xE8hxmoL+2GNuSvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:15:10Z"
    mac: ENC[AES256_GCM,data:pO7fBMJ2wL4zy06hl+Xdhstu3idF9EokK1kuWcnhre1OGDVFwqoGlFxbGzz2dja1kG/eiiF+f23Kf+SnpYJIuwkbwirRgIDjqfJMB6kxbXdjmThifpakrM8nThM6S/77MyQvCkKFfeq5J32vXzwtyvHWta6J7SHs7teCFUks6zE=,iv:357aKuI3oeDObTvYIK9s1KQo7CHXaSA2qyseTkDsBCE=,tag:u9YvdK8yRyvhMOaYY82tZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:3FQelZCJpmQzj7jVRaDJyzfM2XgbX3isvED6fA1kxr8=,iv:GNL1nsPvd8X3ndU48v1crHQEfqt6K3u7jFJQwFEq7mA=,tag:aozZ7j5Ei8zHPYaLWqa8hA==,type:str]
    password: ENC[AES256_GCM,data:Yds7pReceNBbiwVj5o8t2NiIJGvNyLCia0gVl1JJN6ExtLz94F8T4/+4T1c=,iv:KhHmJljHEoA5pEjeapVQItP5f1CicgUGL7OEAVH8NgE=,tag:8pmJyXQ+Dkgk3kezsJl+Fw==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MWR2ZloxVFBkcXIvam9N
            OG5tVHNRT1YrMnFmelNjWUJRTXVIT1F5OWlvCk9ZQ0NYUkJpMFRaZlFxeGtDQ2cy
            UzU5Y3AvY3NCa2tsMzFzaFRFVmp5LzgKLS0tIG1CbktlT1ZqaTU4b3hVdS9FbnFB
            S1BtbWVQQXJDS1h5VzdiRW11WW52dm8KoL3ZE/TE0poOOOzjl8o7XP5y8ybAGowz
            KpLeOesx+RmiX1AO8YBjUFG3pRy5ABPLAFOo/xE8hxmoL+2GNuSvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:15:10Z"
    mac: ENC[AES256_GCM,data:pO7fBMJ2wL4zy06hl+Xdhstu3idF9EokK1kuWcnhre1OGDVFwqoGlFxbGzz2dja1kG/eiiF+f23Kf+SnpYJIuwkbwirRgIDjqfJMB6kxbXdjmThifpakrM8nThM6S/77MyQvCkKFfeq5J32vXzwtyvHWta6J7SHs7teCFUks6zE=,iv:357aKuI3oeDObTvYIK9s1KQo7CHXaSA2qyseTkDsBCE=,tag:u9YvdK8yRyvhMOaYY82tZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-user
    namespace: firefly-iii-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:a9YK/A9TwW0YtNRamJhdCx6Q18VOZGTlaQZfJdJx3jY=,iv:vKDwMo4YGl7X42QIHnLZdaBjbyl+FW6kY0K0/zkQSy4=,tag:o0flnErSXqsKyHLys1J7aQ==,type:str]
    password: ENC[AES256_GCM,data:v1rn6fhQZdDp2VywVANmiD/+mVRO0W5g7IX5YVNJ5L5KXoiilHuFzArcYyM=,iv:yT0VsKQCKWybUs0E8vhIBvyKyTFybGAYyUds9BpF1io=,tag:qcFwCWlMKKFAjANlASsGTw==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MWR2ZloxVFBkcXIvam9N
            OG5tVHNRT1YrMnFmelNjWUJRTXVIT1F5OWlvCk9ZQ0NYUkJpMFRaZlFxeGtDQ2cy
            UzU5Y3AvY3NCa2tsMzFzaFRFVmp5LzgKLS0tIG1CbktlT1ZqaTU4b3hVdS9FbnFB
            S1BtbWVQQXJDS1h5VzdiRW11WW52dm8KoL3ZE/TE0poOOOzjl8o7XP5y8ybAGowz
            KpLeOesx+RmiX1AO8YBjUFG3pRy5ABPLAFOo/xE8hxmoL+2GNuSvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:15:10Z"
    mac: ENC[AES256_GCM,data:pO7fBMJ2wL4zy06hl+Xdhstu3idF9EokK1kuWcnhre1OGDVFwqoGlFxbGzz2dja1kG/eiiF+f23Kf+SnpYJIuwkbwirRgIDjqfJMB6kxbXdjmThifpakrM8nThM6S/77MyQvCkKFfeq5J32vXzwtyvHWta6J7SHs7teCFUks6zE=,iv:357aKuI3oeDObTvYIK9s1KQo7CHXaSA2qyseTkDsBCE=,tag:u9YvdK8yRyvhMOaYY82tZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
