# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:pZ17k7KvW9zVYpfS,iv:h61AaxVFR+GcEa9Ps3uGkXjZjgDpy/XrYeOFEi2X9bU=,tag:ajmhTX3qBdw2mQ5xyYUQOQ==,type:str]
    password: ENC[AES256_GCM,data:3FskPTVignlVuHfxrl7zYgByypRu32qb,iv:UUVKNbpz//UVooI/+Kv0CM+brVRdbfnIPE2lHC04XOI=,tag:3x95F1o/hlonBHA7o76btg==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRDZBWVRhblBBTTdmWGNI
            UUg4WEk3OGtyY0FzRkRNc3VXR3NZSTJ5b1drCkdXUmhZSCt2eVhRTUhyYjZZNEgy
            TGwzVlRDUjM2VE40QTZldDAyOEtoZ2cKLS0tIC9XbUpxaXM3aXNFaDZMYXQ1d3hJ
            QVRpVkt3bkV5M3c1b0lMU3BZaXlmMEEK4IkI8cOVtwe0kdpSrxfztbsxmuyPMFkJ
            iXmu+HU5lYBP1oyYB0YbRozVFr8fn/ENxA/eDciIl+QjgW0wn5aprg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-17T22:42:47Z"
    mac: ENC[AES256_GCM,data:gGMJlishxRW544K/OcmTnrZdKxBntY2s/bnnMbOn/qX29rIMOUlhPixWP8ZBu7tg5TfFF7dMsQDtXNBWvs/MmQkvdnbEMQstX+BeyY8KfHmguKbSxqG+ZLQqZuU+jw0LqEwoA/Awsdrpb3mpGhNBQy/U6SGnzv1zZrfOROe2g0c=,iv:fWPlVhCD0SzbJhqHqpZPeYrKimLZyByVqBoPwvufjp8=,tag:sHk90f3+JeMBLq9qNi1kDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:22ee/Fgx82DjB2GUeYkUyJoZYMJZsAEsT02SXF+u/qA=,iv:EyKnSZWXA8JDvrevcQohDfn5C1JFwdAsAwKjfJKFxEA=,tag:apFe+Kl3AC2dQ2TQPm3t9g==,type:str]
    password: ENC[AES256_GCM,data:inKOrypsOT97hkJikijPpp5zn30s9UhXiBoaftusGXXfyPWJCQgOxKiM2k0=,iv:7T/lhIwIJRmPQM1ByM0fqs6gxSMz0i3Q+mpJ7/L3hjc=,tag:p//3DSV5/OuYPrY70JBHyw==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRDZBWVRhblBBTTdmWGNI
            UUg4WEk3OGtyY0FzRkRNc3VXR3NZSTJ5b1drCkdXUmhZSCt2eVhRTUhyYjZZNEgy
            TGwzVlRDUjM2VE40QTZldDAyOEtoZ2cKLS0tIC9XbUpxaXM3aXNFaDZMYXQ1d3hJ
            QVRpVkt3bkV5M3c1b0lMU3BZaXlmMEEK4IkI8cOVtwe0kdpSrxfztbsxmuyPMFkJ
            iXmu+HU5lYBP1oyYB0YbRozVFr8fn/ENxA/eDciIl+QjgW0wn5aprg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-17T22:42:47Z"
    mac: ENC[AES256_GCM,data:gGMJlishxRW544K/OcmTnrZdKxBntY2s/bnnMbOn/qX29rIMOUlhPixWP8ZBu7tg5TfFF7dMsQDtXNBWvs/MmQkvdnbEMQstX+BeyY8KfHmguKbSxqG+ZLQqZuU+jw0LqEwoA/Awsdrpb3mpGhNBQy/U6SGnzv1zZrfOROe2g0c=,iv:fWPlVhCD0SzbJhqHqpZPeYrKimLZyByVqBoPwvufjp8=,tag:sHk90f3+JeMBLq9qNi1kDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
