# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:PKK8BUKWyqEGF7OI,iv:aY8w1L/huSw7NdcAfbFBk8iqj1BTTRAK/uy3SMKxKh4=,tag:RG75YHN+XB13Cn4sowVKew==,type:str]
    password: ENC[AES256_GCM,data:hHBBIcylKCEbyQ6rvgNeZzuNUCTZLmPx,iv:H4E2/iSs/mXc/rWkO63rLXuUwST8WAd1SgZ2dvtI10A=,tag:QP/F/BcOKAc5CHvjDPlajw==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhxMFhaMlZOVkVxdHd1
            Y0h0am1MTkJBYUVlc2t5d0FtUk9Tb2x0bFNJClZTYWxaNURPTi9uVkJtVHhFVVg1
            V3BhQmp2QlFhd0U2RmhaVjFBeXhkR3MKLS0tIG1SVjJtZStVVzZycXA3TmhNS2xM
            UVd3NUM0clJPUkloV0pNYlo1TWE3NmMKJjwp8USlY3vs8TL+I6wLNAgJ0RWxiVMS
            yOvEYOddqObjvotq0ibg/RGlGJUl/ui9gtwegHZHBjtCuqtLL9Jnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T10:25:07Z"
    mac: ENC[AES256_GCM,data:EJKGv+mROJB8gV45HacNU3UH4ASQXMGvhrUOgJqiNVaWCWHgyqO/gDk96Fkmmqno96vBmVjyakKkvyVN0k2lXMYPQKXZNkiiWKmBX7yD01aGi7gjL2UQNnRPCb7H4X1kcy0Ujc58XJRb2VV3vlJPYS2dtY53kFudylJj7cE+wUQ=,iv:Xu0higgS/S8GxA34jV2Gcro895qM8VOBZ5426U0iCm8=,tag:kENSFF+FqyRa5/T7JWL+8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:i+7XpRqwE9MhEt/C6kXzKVHgcbohk5Uy1dwq8Ss7MtE=,iv:1Pw7Z/LVqwcryO9QaqMXAjaV4Wth03T+px4SLTPiL8k=,tag:lEiW9P5SQ/KOHx0etiorNA==,type:str]
    password: ENC[AES256_GCM,data:g/DN4BnQX+WwmZJhSA15J26s+u7HLNa+812366ZV/DHxNDWQiYtN7jG68wg=,iv:r3jSDWZlnVz9moDXBu0WvHlkQkXjbRkk+u40GWP4F3Y=,tag:OQIeuQrljjTTt84dV0fd3g==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhxMFhaMlZOVkVxdHd1
            Y0h0am1MTkJBYUVlc2t5d0FtUk9Tb2x0bFNJClZTYWxaNURPTi9uVkJtVHhFVVg1
            V3BhQmp2QlFhd0U2RmhaVjFBeXhkR3MKLS0tIG1SVjJtZStVVzZycXA3TmhNS2xM
            UVd3NUM0clJPUkloV0pNYlo1TWE3NmMKJjwp8USlY3vs8TL+I6wLNAgJ0RWxiVMS
            yOvEYOddqObjvotq0ibg/RGlGJUl/ui9gtwegHZHBjtCuqtLL9Jnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T10:25:07Z"
    mac: ENC[AES256_GCM,data:EJKGv+mROJB8gV45HacNU3UH4ASQXMGvhrUOgJqiNVaWCWHgyqO/gDk96Fkmmqno96vBmVjyakKkvyVN0k2lXMYPQKXZNkiiWKmBX7yD01aGi7gjL2UQNnRPCb7H4X1kcy0Ujc58XJRb2VV3vlJPYS2dtY53kFudylJj7cE+wUQ=,iv:Xu0higgS/S8GxA34jV2Gcro895qM8VOBZ5426U0iCm8=,tag:kENSFF+FqyRa5/T7JWL+8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
# Secret are namespaced scope in k8s
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-firefly-user
    namespace: firefly-iii-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:iw5T7fhgGWLv8omBc+APko9+0PszoBSRL6BHoCb2yzg=,iv:GEThr4RFynCeVhFMHO3oOyM+9F2iD9w15+sEuSyhMho=,tag:99XaMKvXOqnPvNgY+5ekBA==,type:str]
    password: ENC[AES256_GCM,data:sAsgotKhiCd9pEuTgSbWD6GZ45oP9/Epf0j2DkM0TpORqSY7RgX3uLF3PhU=,iv:B15yYBb4wHcEInFNVYElr453DbxJC/Q7NLetYEVfhXQ=,tag:zGt3I3cpS5IVlOMNR90V9g==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhxMFhaMlZOVkVxdHd1
            Y0h0am1MTkJBYUVlc2t5d0FtUk9Tb2x0bFNJClZTYWxaNURPTi9uVkJtVHhFVVg1
            V3BhQmp2QlFhd0U2RmhaVjFBeXhkR3MKLS0tIG1SVjJtZStVVzZycXA3TmhNS2xM
            UVd3NUM0clJPUkloV0pNYlo1TWE3NmMKJjwp8USlY3vs8TL+I6wLNAgJ0RWxiVMS
            yOvEYOddqObjvotq0ibg/RGlGJUl/ui9gtwegHZHBjtCuqtLL9Jnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T10:25:07Z"
    mac: ENC[AES256_GCM,data:EJKGv+mROJB8gV45HacNU3UH4ASQXMGvhrUOgJqiNVaWCWHgyqO/gDk96Fkmmqno96vBmVjyakKkvyVN0k2lXMYPQKXZNkiiWKmBX7yD01aGi7gjL2UQNnRPCb7H4X1kcy0Ujc58XJRb2VV3vlJPYS2dtY53kFudylJj7cE+wUQ=,iv:Xu0higgS/S8GxA34jV2Gcro895qM8VOBZ5426U0iCm8=,tag:kENSFF+FqyRa5/T7JWL+8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
