# manifests/infrastructure/secrets/cloudnative-cnpg/pg-firefly-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:QdOPQA+xiionG8XC,iv:KthWA2MAz5QJaXuEuw/v77VRJrwiCebyPEY6NZcmFDw=,tag:MwLH0gBhTapKCmhULiexog==,type:str]
    password: ENC[AES256_GCM,data:oHWsknLPx/LYTVVumahYeks7q5OMnVwc,iv:dyjn9Pl+fnLUM7KOdQbgY0i3N9Sps8Ai+FEmmtxzU+E=,tag:po1RLSKN07LKW28919snxg==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOREdHQXVrVVdPTmdxaHFM
            VlFtYnFxS2U3bWdudVR4bFNvazlXdVhtY2dVCmNQcjlEb0FaMElvV2FHMFp4aEow
            TTJPTE5SS0FiRUMwZFJBaWt3aFdHN0UKLS0tIEZqQXlXOU80Nko4OTRETUQ3aUJV
            SmtBcHN5cnkrTG5LTTlqWE9DM2phUEkKBegJaVfT76UaVgrNSmcqGzzDkdELvkTL
            CAmFxJM4WaA4P8Auf0mRqky17MOMAmdP5f3JOl2XrDhcf6b+ds5C2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-17T22:29:26Z"
    mac: ENC[AES256_GCM,data:kyM6bvQanbOC64lHW2avgVTuYAl5F6Z8DLkjR3ICosnmmLl4fnmTV7AqXicD7XTzUzJccyIqc38Xfvg5aA29hqp1pr+63YPdFNHR0zlpAp9Y9ukKusj5uI8k9ivLxqUwS/a1yECizWtT08iNRwvTIMKCmLIhUTm0DHI2cdmgeNg=,iv:jhypQm0qtrkxaHkJxDKiaq0psZtUSxK00JCVWVOevvo=,tag:tGtidye2jAkzUX918QfLCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:mlcRzXJFNlZApIwe5Uskc/Vij0BIYryqyakVAuFRd8A=,iv:RNenuYYIld0qzr9/zbZKalv8m9HOyPDoqcOmHSFPkgU=,tag:iwoRYvfkIzPJXfMAf7bLzA==,type:str]
    password: ENC[AES256_GCM,data:b9yOlvL4FPm1dqbylnRh5Fb0LBlcB3sJ+AvaJnOLX5vWr4+KzGa7rRN8rEI=,iv:Vk0ksWGE+5wxYrgMkXCopbj0b+ZEB0Bfgw6BuOFaYvE=,tag:C1xtXJzJuRhOrc1XLyhFJw==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOREdHQXVrVVdPTmdxaHFM
            VlFtYnFxS2U3bWdudVR4bFNvazlXdVhtY2dVCmNQcjlEb0FaMElvV2FHMFp4aEow
            TTJPTE5SS0FiRUMwZFJBaWt3aFdHN0UKLS0tIEZqQXlXOU80Nko4OTRETUQ3aUJV
            SmtBcHN5cnkrTG5LTTlqWE9DM2phUEkKBegJaVfT76UaVgrNSmcqGzzDkdELvkTL
            CAmFxJM4WaA4P8Auf0mRqky17MOMAmdP5f3JOl2XrDhcf6b+ds5C2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-17T22:29:26Z"
    mac: ENC[AES256_GCM,data:kyM6bvQanbOC64lHW2avgVTuYAl5F6Z8DLkjR3ICosnmmLl4fnmTV7AqXicD7XTzUzJccyIqc38Xfvg5aA29hqp1pr+63YPdFNHR0zlpAp9Y9ukKusj5uI8k9ivLxqUwS/a1yECizWtT08iNRwvTIMKCmLIhUTm0DHI2cdmgeNg=,iv:jhypQm0qtrkxaHkJxDKiaq0psZtUSxK00JCVWVOevvo=,tag:tGtidye2jAkzUX918QfLCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
