# manifests/infrastructure/secrets/cloudnative-cnpg/pg-freshrss-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-freshrss-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:248Maunmt4F0IrHH,iv:WMYLEAe4V+7KSKVmjNpIZvojgkNRW7Mxz6lvS7l/a6s=,tag:rQna89xKjusgC54hSpKF4g==,type:str]
    password: ENC[AES256_GCM,data:HJ67cdk3Npqd0TVGQsRfJZmk3M0rsxr3,iv:4ukoYNDmzppjTAPPgDUJ+3PYETKYAbxqmsOXP13hAjw=,tag:+01aO7DiQxN38MUUOxA85g==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVE5clhaRzNDVldmQ2FD
            aG51alovZHlxV0NTU1hNemluaFFPKzh4aXhFCnNqU2UzTFUxZndlZmtOU2xtMTkw
            TEpIUDA0S1RnSzM0QUNvT0l2Uk44UkEKLS0tIFhDZmpRWU5oekp2SDdsbVNYRUpp
            ejdJOUJlT1V0dlRONm1SYzJUNEdWRjgKuHhwtRQQbQGdf7HEEzkKRoIzFfmeO7ZR
            TMiiunk9lI2b9mW2mGXpfaRFVDVdgcFJf47bZ3a++lyC9+TbMWQ/2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T21:15:34Z"
    mac: ENC[AES256_GCM,data:76GdeeHb+7tF43paAvUCxpwlAvMOtR0jBQmef7mEwiI0dT96Ue6MWbQZZdbEM65eynLHFdnD6BR1c6uPPkEPY4ktJ9r7vdAxjY/Cyzlx3A+FN3z9x++HaxhN6ZWH549z3L39kvVWlFMYFRXP8nBkfUxBFeJ41h2Bq+yRD/1USjU=,iv:rCgnBxme2QFRzaQ5GEvI6GdFHCmyy/gRE2d0n5IV2mY=,tag:JAMB7MBf4rgeAXicvaWdXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-freshrss-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:iTMBnur5fk6l5GLKVjDhhkDmiTVYDT0QGr4LVqov/HmrGd5k,iv:N9kjy/WiijiIG8soflOIWHAIqfms+w6+sPFxYghdVhQ=,tag:BejH8UQzRNCERAGDYUK8QQ==,type:str]
    password: ENC[AES256_GCM,data:YVTbrdAMy3tkt4eswTqLx5BpbufHhDoBy4gsyZ3aIIhVJzmgY0FOBkhoFxw=,iv:IT/KzTRaSPHuosXAQ91y+2leASpXr/nZjEfuQ56Ap4E=,tag:4Q6woS69A8zPhcqODRcY/g==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVE5clhaRzNDVldmQ2FD
            aG51alovZHlxV0NTU1hNemluaFFPKzh4aXhFCnNqU2UzTFUxZndlZmtOU2xtMTkw
            TEpIUDA0S1RnSzM0QUNvT0l2Uk44UkEKLS0tIFhDZmpRWU5oekp2SDdsbVNYRUpp
            ejdJOUJlT1V0dlRONm1SYzJUNEdWRjgKuHhwtRQQbQGdf7HEEzkKRoIzFfmeO7ZR
            TMiiunk9lI2b9mW2mGXpfaRFVDVdgcFJf47bZ3a++lyC9+TbMWQ/2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T21:15:34Z"
    mac: ENC[AES256_GCM,data:76GdeeHb+7tF43paAvUCxpwlAvMOtR0jBQmef7mEwiI0dT96Ue6MWbQZZdbEM65eynLHFdnD6BR1c6uPPkEPY4ktJ9r7vdAxjY/Cyzlx3A+FN3z9x++HaxhN6ZWH549z3L39kvVWlFMYFRXP8nBkfUxBFeJ41h2Bq+yRD/1USjU=,iv:rCgnBxme2QFRzaQ5GEvI6GdFHCmyy/gRE2d0n5IV2mY=,tag:JAMB7MBf4rgeAXicvaWdXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-freshrss-user
    namespace: freshrss-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:tawA6QROMEEeqgwLDxzk3EMlSCCtJPtGF/bFa75mWvueSDt0,iv:pGuRnNtSYBXKiFFSzkqi0CX7r9/9yYe1SyjiSuVxdjk=,tag:Z0erCwRN+l46mzNIZTWXeQ==,type:str]
    password: ENC[AES256_GCM,data:+fSlaLNOIsy6Jn/yh2SKI3+2U/9r5Ek46ia73FC6g5Q25FeRVnbjlyUAoos=,iv:LjcLqAMlI1a2tegLmjb/R8A8dEo0inuzKRPbwbQmvr8=,tag:ACOxnc7zXWNi/SP1iUVP1Q==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVE5clhaRzNDVldmQ2FD
            aG51alovZHlxV0NTU1hNemluaFFPKzh4aXhFCnNqU2UzTFUxZndlZmtOU2xtMTkw
            TEpIUDA0S1RnSzM0QUNvT0l2Uk44UkEKLS0tIFhDZmpRWU5oekp2SDdsbVNYRUpp
            ejdJOUJlT1V0dlRONm1SYzJUNEdWRjgKuHhwtRQQbQGdf7HEEzkKRoIzFfmeO7ZR
            TMiiunk9lI2b9mW2mGXpfaRFVDVdgcFJf47bZ3a++lyC9+TbMWQ/2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T21:15:34Z"
    mac: ENC[AES256_GCM,data:76GdeeHb+7tF43paAvUCxpwlAvMOtR0jBQmef7mEwiI0dT96Ue6MWbQZZdbEM65eynLHFdnD6BR1c6uPPkEPY4ktJ9r7vdAxjY/Cyzlx3A+FN3z9x++HaxhN6ZWH549z3L39kvVWlFMYFRXP8nBkfUxBFeJ41h2Bq+yRD/1USjU=,iv:rCgnBxme2QFRzaQ5GEvI6GdFHCmyy/gRE2d0n5IV2mY=,tag:JAMB7MBf4rgeAXicvaWdXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
