# HomeLab-Kubernetes/manifests/infrastructure/secrets/cloudnative-cnpg/pg-immich-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-immich-superuser
  namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:GkdoxhOm8nGJx6zq,iv:S1rr2TkX6LySeXa1UZbcQemEqIQyI7VE4va5/LsO83Q=,tag:pT7jAXOaBZPMqzdtvxcAeA==,type:str]
  password: ENC[AES256_GCM,data:8K7Mr0bYtzpJ0/uMoVMaPqku2O0rDu28,iv:BdckzAQsTu4Z+EYjG9HfwqpfcauIuiahZ46KSdwX1Lw=,tag:kApl8sZl0DCBkGWs7k97LA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5anUzbE5ONVpQMGJLTTVy
      WkZyemRvZG80YXFDTzdocTBBcGswZ2ZRSmdBCnhwTDBjZjE1Y3lmbmk1V1VJUjVH
      L2lndlRjNGUrTHdmWENsckFEdVcybHcKLS0tIGkrQWRHZFZ3K3JPSHZIZzcrMCtk
      amtDcFhWTUlJd2NDUW15WXEzaXYrcDgKf7rulNc93bgsrlyNR/Vnp5YiEs4h8jfD
      qmG4DfJj/ZuLxYJplOfygPh6YcImxamWC9+RAHGE2NMu0l3NRC3SiQ==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-25T20:54:41Z"
  mac: ENC[AES256_GCM,data:+jwhLnjiXUbBnnPZM4MgsjJGBsD5kHIOcc7Jo7HHsNHLxkwdtVwPpgWJGXGFW6efFew1w2mzL4zw26Pz4Jg/MT0I2/RGMX2/Lk/27DRp6CEZzPa+MuKFGV/hymuiEk11KbCzZGDe7FDvU1zJv3AsleKgo1lmDVuWr+2QmkaX6yU=,iv:+8jLK8i9fPisycEo7DyHS1m8GatGdyDeQUrh/4YFSP0=,tag:iRAyCGq3j+9SRBSODAFw+A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-immich-user
  namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:E+T7UCfRje81mZ31nX1fHuWS5AO7yiXYBB0fZW6GroI=,iv:HdLkjRefNJzdujL6zVOeTWFcNmvRY0hLWY3abI1Tpr4=,tag:uKvqOJ+KeqwAi/rvg8XSUQ==,type:str]
  password: ENC[AES256_GCM,data:jsX860Kdanb+pC9AKqctswZnzWIHp6YZ496U3j6aNbS/1aFk0d1enQ==,iv:WASBJK3rLrPI4BEZ5SLdDeG+f64Ie1Fz1aC1rduL3qg=,tag:cUWbVKm1SJHAOsQpery4qg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5anUzbE5ONVpQMGJLTTVy
      WkZyemRvZG80YXFDTzdocTBBcGswZ2ZRSmdBCnhwTDBjZjE1Y3lmbmk1V1VJUjVH
      L2lndlRjNGUrTHdmWENsckFEdVcybHcKLS0tIGkrQWRHZFZ3K3JPSHZIZzcrMCtk
      amtDcFhWTUlJd2NDUW15WXEzaXYrcDgKf7rulNc93bgsrlyNR/Vnp5YiEs4h8jfD
      qmG4DfJj/ZuLxYJplOfygPh6YcImxamWC9+RAHGE2NMu0l3NRC3SiQ==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-25T20:54:41Z"
  mac: ENC[AES256_GCM,data:+jwhLnjiXUbBnnPZM4MgsjJGBsD5kHIOcc7Jo7HHsNHLxkwdtVwPpgWJGXGFW6efFew1w2mzL4zw26Pz4Jg/MT0I2/RGMX2/Lk/27DRp6CEZzPa+MuKFGV/hymuiEk11KbCzZGDe7FDvU1zJv3AsleKgo1lmDVuWr+2QmkaX6yU=,iv:+8jLK8i9fPisycEo7DyHS1m8GatGdyDeQUrh/4YFSP0=,tag:iRAyCGq3j+9SRBSODAFw+A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
