# manifests/infrastructure/secrets/cloudnative-cnpg/pg-n8n-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:CKPkyWqv3kK27Ko1,iv:AL4vV4Q1syi6aBYvLI/R/UJPd/r2Dt11iUSYuRVUwsQ=,tag:AkPvG1e3KGWKRraxtAE3og==,type:str]
    password: ENC[AES256_GCM,data:tHQ/X8i4z+H/WqmDx0xXOnZMSDdQK4Y9,iv:rLfhlfI/IlyUgfcWKhIVFivD5sQ0FnSmh2sXw4A6kGo=,tag:udrRN0Dv2kjVzge6VCEVnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSjJZMWFQbjY0TTU3YWtv
            VFd0NjNBa1lRNnQ0dmVJQTExNk9JY0JoOHdRCjk2WjlwZGNIR3R4MW1LYTBZb3k1
            Rnh2N1FpRXE1ZzJoT25MeG5PZ05RRzgKLS0tIGNQK2tVbGR1QzZacVNMUXNOUE9x
            TVJIU2x5T29xZjN2czZTenBLOUJneTQK6COY4LMNigYN657+cjR53e4fJEUZKKjH
            voTnA0bE8IjM7CWo+6M/mV/xPGfTAVh57dj59my8AW1FqbYDpZDVTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T09:31:53Z"
    mac: ENC[AES256_GCM,data:813sE04qAwYxoTqYteCdOB06GIiIP6213d7LnKl0mYQaEwKFsxw65hz07gIBIvRd97uc330nzECZgWdiUY7bqIgC/ZO6jpCTiT9HPq26zOyyNBklJn2DfjhtFjsd/G9qnPb19nF4XIu8Nw0v14Uo7NXiwWNuOb3Ql26wxWnnjsw=,iv:2IKRYkd7owRAq3S0LrITnDTP5QxYL3tbV71TDYYOMmk=,tag:ebPWJRb7e2OAK+D8OW6/XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-n8n-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:qngvVBN6bjOeOgqhhXcBsqRODk56AhMUYD4uPg==,iv:WdsFGtwdGyZ3ZzeVwnjzPRpnRCEgxKKtWDh25Oi+RrM=,tag:yOFZNOJpJu+cjAueea8+Lw==,type:str]
    password: ENC[AES256_GCM,data:vWEZ7h62DXdrX6K9ARYv4IJ3LtF+JCnUI8t2NV6Ew1P9U2Ko,iv:o19UNNFFdiVh/TBUhbwBLMeD+dxTFUAD2BkiNFJ9QXo=,tag:hyWAaWTafK+mhdItGeFgtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSjJZMWFQbjY0TTU3YWtv
            VFd0NjNBa1lRNnQ0dmVJQTExNk9JY0JoOHdRCjk2WjlwZGNIR3R4MW1LYTBZb3k1
            Rnh2N1FpRXE1ZzJoT25MeG5PZ05RRzgKLS0tIGNQK2tVbGR1QzZacVNMUXNOUE9x
            TVJIU2x5T29xZjN2czZTenBLOUJneTQK6COY4LMNigYN657+cjR53e4fJEUZKKjH
            voTnA0bE8IjM7CWo+6M/mV/xPGfTAVh57dj59my8AW1FqbYDpZDVTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T09:31:53Z"
    mac: ENC[AES256_GCM,data:813sE04qAwYxoTqYteCdOB06GIiIP6213d7LnKl0mYQaEwKFsxw65hz07gIBIvRd97uc330nzECZgWdiUY7bqIgC/ZO6jpCTiT9HPq26zOyyNBklJn2DfjhtFjsd/G9qnPb19nF4XIu8Nw0v14Uo7NXiwWNuOb3Ql26wxWnnjsw=,iv:2IKRYkd7owRAq3S0LrITnDTP5QxYL3tbV71TDYYOMmk=,tag:ebPWJRb7e2OAK+D8OW6/XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
