# manifests/infrastructure/secrets/cloudnative-cnpg/pg-openlit-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-openlit-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:NjCp0y6iGq0=,iv:J5T81imJ4epm47OZz18IUFaI7KzCMNJTpVBOAQD3Kkg=,tag:hU2cZEiKS0SqolxYzf62lQ==,type:str]
    password: ENC[AES256_GCM,data:Fiyjgs3at1AfPaeqt80KC70L,iv:l1+kPx7J5igBmTdprCMzI3KijeVEKGmB+YWUZGJGHQc=,tag:7a9XgD8EYC/kVwmU4ifK9g==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVVsMjNoUTRhbkE1UkVY
            cFE5M3NzTkg4ZHFTNVBJYnE4R2FpV3ByOVFzCjlNcUVTRXZjakd0UitjMGZsMkVQ
            eFkraTMvOU1ucldjdko1Y1FGaUlsVzQKLS0tIG5kZGVCN1g0NnJQVlZTTktybWls
            WmkxZ1ZpQlVCdWxRU0UwSEJIV2JabmMK/orlDR30ox/ABJoLUD2JpGdnfllqXIs2
            cfAXzjGdEUE3Orvu+skjCXGRGV4j9F7T5RazjMEHKsfFSA6lDahc5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:38:21Z"
    mac: ENC[AES256_GCM,data:G3ZGbuTdfnddS9xujm+mGhzYCrAUmqMaUEKqEp9csym3Ji2PSRLSA+EVVA99vJOTBBusXLskJi9OP25yiq1c8qIvo2niE40/vXYTZtuHv+ks7lyG/O7tmWHWQjMQPcjQuxLC0edcGCWhKPSYACojegYMK6+LNF5AIzJ3b0fYeuc=,iv:+q/jAVB7nnkN6XorR9jFefbgN3Swnq0xIYJblnonqfc=,tag:WOp6Tlki/b0dVM7MDmDtng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-openlit-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:iApIZk1/psidlmUCJhV+W3bBME7PZv4S,iv:q0IwXdRKLkuBU+PuGWEeJIyZeT+DZr/z0oEqngPJYeY=,tag:rnPJK6GKDB3gAUFaXyIBdw==,type:str]
    password: ENC[AES256_GCM,data:/C1rVRL2Z5A6OzS5wjGDE3mcKGdF3TSHOo8l3TyCjQ==,iv:mGFhay+VUZsUFU4Y8QPioqKw0LtewlPHgNR7h8yHXCc=,tag:67ubHf8gbmUxp0SqbhYEEQ==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVVsMjNoUTRhbkE1UkVY
            cFE5M3NzTkg4ZHFTNVBJYnE4R2FpV3ByOVFzCjlNcUVTRXZjakd0UitjMGZsMkVQ
            eFkraTMvOU1ucldjdko1Y1FGaUlsVzQKLS0tIG5kZGVCN1g0NnJQVlZTTktybWls
            WmkxZ1ZpQlVCdWxRU0UwSEJIV2JabmMK/orlDR30ox/ABJoLUD2JpGdnfllqXIs2
            cfAXzjGdEUE3Orvu+skjCXGRGV4j9F7T5RazjMEHKsfFSA6lDahc5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:38:21Z"
    mac: ENC[AES256_GCM,data:G3ZGbuTdfnddS9xujm+mGhzYCrAUmqMaUEKqEp9csym3Ji2PSRLSA+EVVA99vJOTBBusXLskJi9OP25yiq1c8qIvo2niE40/vXYTZtuHv+ks7lyG/O7tmWHWQjMQPcjQuxLC0edcGCWhKPSYACojegYMK6+LNF5AIzJ3b0fYeuc=,iv:+q/jAVB7nnkN6XorR9jFefbgN3Swnq0xIYJblnonqfc=,tag:WOp6Tlki/b0dVM7MDmDtng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-openlit-user
    namespace: openlit
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:f8DXSXA2eE6ElRV5knH2S4g++Ahf4Fue,iv:Co8dActPpKj855WY84hlElvt40CJGud8vuoqwO1hiO0=,tag:2spXvKm42iqYKbftlLixYA==,type:str]
    password: ENC[AES256_GCM,data:yLpQX8JujpVC2srjb/91FTy3lM/cNbuM95+YtPgjTQ==,iv:ZhyLx0fyupWoxGMtynch0QpsvGYKw2P02tK9bHSEyBQ=,tag:LW5+bK0tGlEuobFX5PEY2w==,type:str]
sops:
    age:
      - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVVsMjNoUTRhbkE1UkVY
            cFE5M3NzTkg4ZHFTNVBJYnE4R2FpV3ByOVFzCjlNcUVTRXZjakd0UitjMGZsMkVQ
            eFkraTMvOU1ucldjdko1Y1FGaUlsVzQKLS0tIG5kZGVCN1g0NnJQVlZTTktybWls
            WmkxZ1ZpQlVCdWxRU0UwSEJIV2JabmMK/orlDR30ox/ABJoLUD2JpGdnfllqXIs2
            cfAXzjGdEUE3Orvu+skjCXGRGV4j9F7T5RazjMEHKsfFSA6lDahc5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:38:21Z"
    mac: ENC[AES256_GCM,data:G3ZGbuTdfnddS9xujm+mGhzYCrAUmqMaUEKqEp9csym3Ji2PSRLSA+EVVA99vJOTBBusXLskJi9OP25yiq1c8qIvo2niE40/vXYTZtuHv+ks7lyG/O7tmWHWQjMQPcjQuxLC0edcGCWhKPSYACojegYMK6+LNF5AIzJ3b0fYeuc=,iv:+q/jAVB7nnkN6XorR9jFefbgN3Swnq0xIYJblnonqfc=,tag:WOp6Tlki/b0dVM7MDmDtng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
