# manifests/infrastructure/secrets/cloudnative-cnpg/pg-openlit-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-openlit-superuser
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:Ru/Kipq+FdUmcnu4,iv:8LIry64tBQWZPr8NXgbxgyHJGt8ZEy0qyM10dFsD5Jc=,tag:chmnkN0hgVtJsNKAylsGrQ==,type:str]
    password: ENC[AES256_GCM,data:qbRAxNtTTPsmL3tq+v277C8MPN2WbwWz,iv:Gd+NOfjmO7/UixAr87NiHih/7fQtc7d46SeuO8DvcP8=,tag:y/rEV/xj9tqsdh1cDm9skA==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eDNWcUUxMU9SSGhsZ0FW
            VzdMblhVRUlmWGF6enNXa1N6N3c3SlQ4M0hFCmhqVFRDNVAwendubG9MWWROSDBi
            Q2ZMV2pobndCYjVkamIrT1BRRTN4ZzQKLS0tIHNXRy9zOXIraTFHcnQxa2FMaVU3
            QzJkQlNVTXZsbDVaRXVIeGwyUTZNbkUKkMpPfqqckg01XOuAYYhKQdAdNbTznkU/
            +g1jZJ/jAWVAyMm3rY0dyieXQWnoqZp0stblzOEzJcxmlw6FDFU6nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:59:48Z"
    mac: ENC[AES256_GCM,data:t8A8IiBjgu55OOE6RTwI9Dywtdb5bacZygKzgeKaNMsb6Vlzw/B3BhLol2OqCk0dwCR0+7Notdk4wWWLolfHwYftl/xtqYfsU0GmNltCGzS4aGDOFM/hvFjUSm4v3Ar+TAHz5CPV5xOPNNxqFxPxkV7c017Lwfjx/U5oe1mg4Sk=,iv:K5WIypOeTMFkU0VtTVHpLlcLvh3gO9mhwptTzhvWTdQ=,tag:ATDHZS9eCIKtliakMjuVXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-openlit-user
    namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:8e1sY1L8SEtW327m+H5Gp75Hd7MAfgbK1XzYlMWEPGg=,iv:EZ8Xta9hwnjM7WkOsVIIb3H+5jxsYf6C9boCWFpfHLs=,tag:MLrx0RftTq1qTWcc1I9uzg==,type:str]
    password: ENC[AES256_GCM,data:j+vl68XtL/cuXFYvJb+SULFWRA44wJdIgFpNDjByWcPaVZ5WLiP4RKwCmeM=,iv:3h1sDEv8CarRkKG71ODfX2mLefzMOhqSJH1ZuJhpZZ8=,tag:DORaj/LYtDSQVxHy8Mw/6g==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eDNWcUUxMU9SSGhsZ0FW
            VzdMblhVRUlmWGF6enNXa1N6N3c3SlQ4M0hFCmhqVFRDNVAwendubG9MWWROSDBi
            Q2ZMV2pobndCYjVkamIrT1BRRTN4ZzQKLS0tIHNXRy9zOXIraTFHcnQxa2FMaVU3
            QzJkQlNVTXZsbDVaRXVIeGwyUTZNbkUKkMpPfqqckg01XOuAYYhKQdAdNbTznkU/
            +g1jZJ/jAWVAyMm3rY0dyieXQWnoqZp0stblzOEzJcxmlw6FDFU6nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:59:48Z"
    mac: ENC[AES256_GCM,data:t8A8IiBjgu55OOE6RTwI9Dywtdb5bacZygKzgeKaNMsb6Vlzw/B3BhLol2OqCk0dwCR0+7Notdk4wWWLolfHwYftl/xtqYfsU0GmNltCGzS4aGDOFM/hvFjUSm4v3Ar+TAHz5CPV5xOPNNxqFxPxkV7c017Lwfjx/U5oe1mg4Sk=,iv:K5WIypOeTMFkU0VtTVHpLlcLvh3gO9mhwptTzhvWTdQ=,tag:ATDHZS9eCIKtliakMjuVXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-openlit-user
    namespace: openlit
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:nfYgSQM+XOyVZ28ubczDNyojyIqXOCEwpG566qeZq9c=,iv:LR5gNCC78DNNT9OSoGY6+Ca8aFmcYvQacA5C/k5Se/I=,tag:FMZriIiiahvl/WHudxbZJg==,type:str]
    password: ENC[AES256_GCM,data:qqsETGB4bkDLwZZQcpPKCDuHVFZC4ShNFsMqv4pWD9ZXJXug4dljBzRKboY=,iv:+mnOr8qnpIIrrz0DZmGSmBT21z1llPgGOp5h1xpBmlc=,tag:RMECXHT+n+6APwssvFTn3Q==,type:str]
sops:
    age:
        - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eDNWcUUxMU9SSGhsZ0FW
            VzdMblhVRUlmWGF6enNXa1N6N3c3SlQ4M0hFCmhqVFRDNVAwendubG9MWWROSDBi
            Q2ZMV2pobndCYjVkamIrT1BRRTN4ZzQKLS0tIHNXRy9zOXIraTFHcnQxa2FMaVU3
            QzJkQlNVTXZsbDVaRXVIeGwyUTZNbkUKkMpPfqqckg01XOuAYYhKQdAdNbTznkU/
            +g1jZJ/jAWVAyMm3rY0dyieXQWnoqZp0stblzOEzJcxmlw6FDFU6nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:59:48Z"
    mac: ENC[AES256_GCM,data:t8A8IiBjgu55OOE6RTwI9Dywtdb5bacZygKzgeKaNMsb6Vlzw/B3BhLol2OqCk0dwCR0+7Notdk4wWWLolfHwYftl/xtqYfsU0GmNltCGzS4aGDOFM/hvFjUSm4v3Ar+TAHz5CPV5xOPNNxqFxPxkV7c017Lwfjx/U5oe1mg4Sk=,iv:K5WIypOeTMFkU0VtTVHpLlcLvh3gO9mhwptTzhvWTdQ=,tag:ATDHZS9eCIKtliakMjuVXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
