# HomeLab-Kubernetes/manifests/infrastructure/secrets/cloudnative-cnpg/pg-paperless-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-paperless-superuser
  namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:NLhTOddwrVSlYCod,iv:4Im7MNrYLpgpw6cRVk14Qyx+eVEoqJ1GfbgSJkQJyZs=,tag:xQfQsYsYG44JI9iTu5nreg==,type:str]
  password: ENC[AES256_GCM,data:lx47k6idsWa+KhJiKLlC1ZkkTK02aO5I,iv:L0133lUICZMShTHrT8d8alkDolhQrI665rQQ/cPMZYw=,tag:9HggEudK09Hetn686juiWA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U2RKMzZINHY3M0RjaFhD
      ajdTOWNraGVlNkQ2YjBrMndNQThIYWdRdVF3Ckl4RU1sc2xkaFhEem5pZVJMOXlH
      TXArYXhQQVYvcGFiMUIwdGxjOVAxalUKLS0tIGt2ajU5dC8rS1d6UUtpTlFtcHln
      ckpHUFR1aE5WS1EweGF6NGJRKzFMWkkK5DubkceuTA3p7Bt1jUJjH5JYIgfDh1V/
      xa+dndqsoxPOiWSUUqc33gK4e+0uOGz1ZtUp9QT+3XHUXVBguZ6/Mw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-24T08:14:59Z"
  mac: ENC[AES256_GCM,data:paZemu29gAkIjHn3JEV1Je2PkU97SwwAG77jqVh/SqD4c9/GmsYQMwC2t6lUsA3rFrTGlAd+n53JYMMo6mURYW+y/qj4Dkl+TVJ6ASv4dPM3AUOHAatBEd3m+0f+xWzty9gNUptzQ2g7n0VkqXZwS4j2GUIDWoausJipapnUM90=,iv:0Lt9RBvYW4Hw5ZnTpSoeHlwPtPbVLXI2sSdh2RnuAtI=,tag:lEl/Oe7gSfg9r2ypczqDBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-paperless-user
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:S6JmkvY//6OCksJ6H8VoN7y04F0=,iv:G/2IfvyIvHhLgKxwQAowey7S51fIZnxKvrpQICXQ6iI=,tag:65eCGSo+8XoiCA+x7fAW1Q==,type:str]
  password: ENC[AES256_GCM,data:VQgaFuY4ctdmLI4TUTVNVAYYwjrmhCEf4VOFs5JM2uU=,iv:CLRlOB3gU5PkoxpNr2VyXamYpmWgl5WE5wt588OUAII=,tag:8bn8qIDmKo2wIDMJOu94IQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U2RKMzZINHY3M0RjaFhD
      ajdTOWNraGVlNkQ2YjBrMndNQThIYWdRdVF3Ckl4RU1sc2xkaFhEem5pZVJMOXlH
      TXArYXhQQVYvcGFiMUIwdGxjOVAxalUKLS0tIGt2ajU5dC8rS1d6UUtpTlFtcHln
      ckpHUFR1aE5WS1EweGF6NGJRKzFMWkkK5DubkceuTA3p7Bt1jUJjH5JYIgfDh1V/
      xa+dndqsoxPOiWSUUqc33gK4e+0uOGz1ZtUp9QT+3XHUXVBguZ6/Mw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-24T08:14:59Z"
  mac: ENC[AES256_GCM,data:paZemu29gAkIjHn3JEV1Je2PkU97SwwAG77jqVh/SqD4c9/GmsYQMwC2t6lUsA3rFrTGlAd+n53JYMMo6mURYW+y/qj4Dkl+TVJ6ASv4dPM3AUOHAatBEd3m+0f+xWzty9gNUptzQ2g7n0VkqXZwS4j2GUIDWoausJipapnUM90=,iv:0Lt9RBvYW4Hw5ZnTpSoeHlwPtPbVLXI2sSdh2RnuAtI=,tag:lEl/Oe7gSfg9r2ypczqDBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
