# HomeLab-Kubernetes/manifests/infrastructure/secrets/cloudnative-cnpg/pg-paperless-cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-paperless-superuser
  namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:jqCsPcGAnaIqhzsl,iv:J8jJeFs0/ncAdPd6NNhswruFjL/3m9yfUJ68zXhenGU=,tag:M48KrrRrRghTmkw5Ab4PmA==,type:str]
  password: ENC[AES256_GCM,data:/IH59cQaI1W9RlZqHXep0xfPZEgCqpwK,iv:6spQ6E2UG3Rkj2lrqs8TLRsxotsuvOX0+ajCsyvBYoE=,tag:rbsGmX6GInF11QRqYlK4zg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb05qZzdVenZoelhrVS95
      T3FvaUdGcy9xUHBuSlVIalhvM2tZMGFPbmlZCkFSTjZrb0p0dktxdGZRUHlCbW1z
      RGxFK1htM0o2NENlbXljZzlmeXE0YmsKLS0tIGkwOXp6Yzgzekx1MzVoMGRPVHFT
      SnQwS1B1S3ZGWVFzZ2h4Z3VIZ29DelkKuMjX3TsU36W2K35O78uKOLVmLlPtdFlL
      i4lo8dBgpJwZ3L2dAkLBlMQTjRkZUvoxTLUpYOvyLg1Ux8SW+DY22Q==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-24T21:31:03Z"
  mac: ENC[AES256_GCM,data:xAsGY2K5c4tm1+pn30vlX6qjkwrN52IebNsWn5CqonFlIG4/K+TdZxoNOSAVa9RqE/9VRAHo1RJ7X8OmovQ0atOfsFB5GQLs2kBrZKLqxG2GZN5ryTKN5YeyTOoL4h1nTtaGIhlTPQwYy1wXQX/bfPsLKBMWO1n1na8g6BtZGd4=,iv:lxj5ToAKZ1w7Id46+Il2IX63NW3fDtm7AF7w2curvGw=,tag:1siKPoskFnMo6/U533irUg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-paperless-user
  namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
  username: ENC[AES256_GCM,data:qRW5m1i0nEWhjWp29KCJ4mWtxYI=,iv:URtQB1WgApjQUiOP60vKITLb1R/sLN0GfiL0mbTpAeQ=,tag:/xT1BKXFW9u75yRhbD8Amw==,type:str]
  password: ENC[AES256_GCM,data:bq5gIBObnvSZnwKxZ18/zhuEHThSbQnAQ2z+x5YKxsc=,iv:LJsusY1tuarH/9EnAafXu41eV3ur3B6KfUMk9hIs9Og=,tag:i3plzcC0WrNJMTAzHZq+jg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1aswzlt70svxa7psprzuuu4aqghetq6pzp7eyqtah9st28cpp539sp04d3c
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb05qZzdVenZoelhrVS95
      T3FvaUdGcy9xUHBuSlVIalhvM2tZMGFPbmlZCkFSTjZrb0p0dktxdGZRUHlCbW1z
      RGxFK1htM0o2NENlbXljZzlmeXE0YmsKLS0tIGkwOXp6Yzgzekx1MzVoMGRPVHFT
      SnQwS1B1S3ZGWVFzZ2h4Z3VIZ29DelkKuMjX3TsU36W2K35O78uKOLVmLlPtdFlL
      i4lo8dBgpJwZ3L2dAkLBlMQTjRkZUvoxTLUpYOvyLg1Ux8SW+DY22Q==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-24T21:31:03Z"
  mac: ENC[AES256_GCM,data:xAsGY2K5c4tm1+pn30vlX6qjkwrN52IebNsWn5CqonFlIG4/K+TdZxoNOSAVa9RqE/9VRAHo1RJ7X8OmovQ0atOfsFB5GQLs2kBrZKLqxG2GZN5ryTKN5YeyTOoL4h1nTtaGIhlTPQwYy1wXQX/bfPsLKBMWO1n1na8g6BtZGd4=,iv:lxj5ToAKZ1w7Id46+Il2IX63NW3fDtm7AF7w2curvGw=,tag:1siKPoskFnMo6/U533irUg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
