# manifests/infrastructure/cloudnative-pg/pg-firefly-cluster.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-firefly-pv
  namespace: cnpg-system
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: ssd-nvme-predator-gm7000
  hostPath:
    path: /var/mnt/ssd_nvme_predator_GM7000/cloudnative-pg/firefly
    type: DirectoryOrCreate
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-firefly-cluster
  namespace: cnpg-system
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  storage:
    size: 10Gi
    storageClass: ssd-nvme-predator-gm7000
  superuserSecret:
    name: cnpg-firefly-superuser
  bootstrap:
    initdb:
      database: firefly
      owner: postgresql_firefly_pgsql
      secret:
        name: cnpg-firefly-user
  monitoring:
    enablePodMonitor: true
