# HomeLab-Kubernetes/manifests/infrastructure/cloudnative-pg/pg-firefly-auto-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
    name: firefly-pg-cluster-backup-auto
spec:
    method: barmanObjectStore
    cluster:
        name: firefly-pg-cluster
    schedule: "0 3 * * *"
