# HomeLab-Kubernetes/manifests/infrastructure/cloudnative-pg/pg-immich-manual-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-paperless-cluster-backup-manual
spec:
  method: barmanObjectStore
  cluster:
    name: pg-paperless-cluster
