# HomeLab-Kubernetes/manifests/infrastructure/cloudnative-pg/pg-paperless-cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-paperless-cluster
  namespace: cnpg-system
spec:
  affinity:
    nodeSelector:
      kubernetes.io/hostname: i1-1806-talos-worker01
  instances: 1
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: local-path
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: Paperless-pgsql
      owner: Paperless-pgsql
      secret:
        name: cnpg-paperless-user
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://i1-1806/
      endpointURL: https://dd8f22ea55fe9ce597a761450466a67f.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: r2-backup-restore-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: r2-backup-restore-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
  #   recovery:
  #     database: Paperless-pgsql
  #     owner: Paperless-pgsql
  #     secret:
  #       name: post-init-paperless-sql-secret
  #     backup:
  #       name: pg-paperless-cluster-backup-20240401000000
