# HomeLab-Kubernetes/manifests/infrastructure/cloudnative-pg/pg-paperless-auto-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-paperless-cluster-backup
  namespace: cnpg-system
spec:
  schedule: "0 30 23 * * *"
  backupOwnerReference: cluster
  cluster:
    name: pg-paperless-cluster
